### ISSUE TITLE
Method to get path of bds script?

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#104]
I was wondering if there is a function or system var. that returns the path of the bds script. In my project code, there are a lot of *.sh and *.py scripts called in the bds script and they are in the same directory (where .bds is in). I actually want to add bds script directory to the env. var. $PATH.

For example,
```
$cd /scratch/temp
$bds /my/script/directory/test.bds
```

```
print("$PWD\n");  // PWD returns working directory (/scratch/temp)
print("$PBDS\n");  // looking for system variables pointing to the script directory...

task {
   sys export PATH=${PATH}:$PBDS
   sys python test.py
   sys test.sh
}
```

Thanks,

**Comment by pcingola** [comment]
Try using 'ppwd' (which is equivalent to running 'pwd -p' in your shell)

**Comment by pcingola** [comment]
You can also use PWD and any other shell variable (the values are the ones defined at the beginning of the script).

**Comment by leepc12** [comment]
Sorry, I didn't explain my situation correctly. 

My working directory is different from the bds script directory

```
cd $WORK_DIR
bds $CODE_DIR/test.bds 
```

$ppwd and $PWD return $WORK_DIR, which i don't want. I need to have a function or variable that returns absolute path of $CODE_DIR.

**Comment by leepc12** [comment]
I found the solution.
```
SCRIPT_PATH := "$ppwd/$programPath"
```
Thanks!
