### ISSUE TITLE
Math functions (round, ceil, floor)

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#109]
I found that bds doesn't have basic math functions like round, ceil and floor.

**Comment by pcingola** [comment]
OK, I'll add them.
If you have a list of functions, let me know (just to make sure i don't forget one that you need).

**Comment by pcingola** [comment]
Added all Java's Math.* functions.
e.g. if you do "sin(x)" it calls Math.sin(x) in java.
