### ISSUE TITLE
request for bds binary location

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#110]
Hello, 

I am writing up automated installation script for my pipeline dependencies including BDS. I found the following URL for BDS binary. but there is a version number in the URL. 

https://github.com/pcingola/BigDataScript/releases/download/v0.999k/bds_Linux.tgz

Could you make a PERMANENT LINK without version number to latest version of BDS binary like the following?

https://github.com/pcingola/BigDataScript/releases/download/latest/bds_Linux.tgz

**Comment by pcingola** [comment]
Actually, you can use the binaries in bds's "distro" folder (GitHub):
    https://github.com/pcingola/BigDataScript/blob/master/distro/bds_Linux.tgz?raw=true
    https://github.com/pcingola/BigDataScript/blob/master/distro/bds_Darwin.tgz?raw=true

I'll try to add the links to the documentation.

**Comment by pcingola** [comment]
Added to download page.

**Comment by leepc12** [comment]
We have 0.999k on https://github.com/pcingola/BigDataScript/tree/master/distro

Could you update it to 0.999l?

**Comment by pcingola** [comment]
I'll update soon (I'm finishing the Math functions you requested).
