### ISSUE TITLE
Regular expression support in strings as filenames

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#112]
Some of my files are named sample_1.fastq.gz,
Others are named sample.fastq.1.gz

When I use file.replace(".gz", "").replace(".fastq", ""), I'd like to specify that the match should be at the end of the string.  Using perl regex as an example, I mean:

file.replace(".gz$", "").replace(".fastq$", "")

**Comment by pcingola** [comment]
For that specific case, how about using string.removeExt() or string.swapExt()?
E.g.:

'file.fastq'.removeExt(".gz").swapExt("bam")
=> 'file.bam'
