### ISSUE TITLE
qstat not found in starcluster created cluster, but qstat is in path.

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#114]
java.lang.RuntimeException: Cannot execute commnads: 'qstat -f -j 969'
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.run(Exec.java:80)
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.exec(Exec.java:37)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.ExecutionerCluster.postMortemInfo(ExecutionerCluster.java:343)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateFinished(Executioner.java:717)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateStates(Executioner.java:778)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:304)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoop(Executioner.java:426)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:383)
        at ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)

**Comment by pcingola** [comment]
Your report provides little information and context, so I really don't think I can help debugging what's wrong in your local configuration...
Can you provide a minimal bds script example, the debug run (using "-d" command line option) and some information on what kind of setup/cluster you are using?

**Comment by golharam** [comment]
Its not consistent.  It seems to only happen when there are lots of jobs in
the queue.  I only have 1 task in my script:

    task ([localfq1,localfq2] <- [fastq1,fastq2], taskName:="Download
$sample") {
        sys aws s3 cp $fastq1 $localfq1; \
                    aws s3 cp $fastq2 $localfq2
    }

I have about 480 samples, and I'm running a 20-node cluster created with
StarCluster.

Where is qstat being called from?  Only from the master bds process or also
on the compute nodes?

**Comment by golharam** [comment]
java.lang.RuntimeException: Cannot execute commnads: 'qstat'
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.run(Exec.java:80)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.exec(Exec.java:37)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.CheckTasksRunning.runCommand(CheckTasksRunning.java:226)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.CheckTasksRunning.check(CheckTasksRunning.java:80)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:313)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoop(Executioner.java:409)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:383)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
Exception in thread "Thread-11" java.lang.RuntimeException: Cannot execute
commnads: 'qstat -f -j 1524'
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.run(Exec.java:80)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.exec(Exec.java:37)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.ExecutionerCluster.postMortemInfo(ExecutionerCluster.java:343)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateFinished(Executioner.java:717)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateStates(Executioner.java:778)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:304)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoopAfter(Executioner.java:436)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:397)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)

**Comment by pcingola** [comment]
Hi Ryan,
  I think it might be related to problems / issues in the head node getting over some user limits 
imposed by the OS. One option would be the max number of threads per user OS limit 
being hit. Bds has a 'maxThreads' in the bds.config file which you can try to lower in order 
to avoid this problem. Another option that comes to mind, would be the max number of file 
descriptors, but recent bds version should not have this problem...
  I hope this helps

    Pablo

**Comment by golharam** [comment]
Hi Pablo - I'm using the latest version available on Github but still
running into this.  how can I check?

**Comment by pcingola** [comment]
Can you try to dump both STDOUT and STDERR to an output 
file so I can take a look at the full error message?

**Comment by golharam** [comment]
Sure.  Let me come back to this.  I have an analysis running and I don't
want to interrupt it.

Also - I was looking at the BDS code and was thinking it may be nice to
separate the AST of the script from the actual execution.  Then, generalize
the execution (local, sge, whatever).  It looks like the code is sort of
tied together, maybe I'm wrong though.  I was thinking this because I think
having Unit Tests in place and allowing users to write their own classes to
handle task execution may be helpful.

Ryan

**Comment by pcingola** [comment]
Hi Ryan,
  I'm not sure what you mean, but the RAST (runnable AST) is just an implementation of the 'bds' interpreter. Tasks are handled using Executors objects which are architecture specific (e.g. SGE, local, etc.). That being said, I agree that there is always room for better modularity and decoupling. 
  Needles to say, if you want to improve any aspect of the code, PRs are more than welcome.
  Cheers.

    Pablo

**Comment by pcingola** [comment]
One more thing: There is a "Generic cluster" system which you can use to incorporate new systems by writing your own scripts (shell, perl, python or whatever), so you don't even need write Java if you don't want.

**Comment by golharam** [comment]
Hi Pablo - I discovered that 'ulimit -n' was set to 1024.  I increased it
to 65536, but I'm still running into the same problem:

java.lang.RuntimeException: Cannot execute commnads: 'qstat'
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.run(Exec.java:80)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.exec(Exec.java:37)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.CheckTasksRunning.runCommand(CheckTasksRunning.java:226)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.CheckTasksRunning.check(CheckTasksRunning.java:80)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:313)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoop(Executioner.java:409)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:383)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
Exception in thread "Thread-11" java.lang.RuntimeException: Cannot execute
commnads: 'qstat -f -j 57'
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.run(Exec.java:80)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.exec(Exec.java:37)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.ExecutionerCluster.postMortemInfo(ExecutionerCluster.java:343)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateFinished(Executioner.java:717)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateStates(Executioner.java:778)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:304)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoopAfter(Executioner.java:436)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:397)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
Task failed:
        Program & line     : 'ExomePipeline.bds', line 314
        Task Name          : '10162 indelTargetCreator'
        Task ID            :
'ExomePipeline.bds.20151015_220652_074/task.ExomePipeline.10162_indelTargetCreator.line_314.id_65'
        Task PID           : '57'
        Task hint          : ' /ngs/apps/jre1.7.0_67/bin/java -Xmx56G -jar
/ngs/apps/GenomeAnalysisTK-2015.1-3-g53415c9/GenomeAnalysisTK.jar \'
        Task resources     : 'cpus: 32  mem: -1.0 B     timeout: 86400
wall-timeout: 86400'
        State              : 'KILLED'
        Dependency state   : 'ERROR'
        Retries available  : '1'
        Input files        :
'[/ngsprojects/NAV1.7_481SampleCohort/analysis/intermediate/10162.dedup.bam]'
        Output files       :
'[/ngsprojects/NAV1.7_481SampleCohort/analysis/intermediate/10162.indelrealigner.list]'
        Script file        :
'/ngsprojects/NAV1.7_481SampleCohort/ExomePipeline.bds.20151015_220652_074/task.ExomePipeline.10162_indelTargetCreator.line_314.id_65.
sh'
        Exit status        : '3'


This is using the latest version from github.  I'd like to debug this and
figure out what is going on, but it may take sometime, unless you have some
ideas.

**Comment by pcingola** [comment]
In a previous message I mentioned "number of threads", have you checked that? 
You can set a lower limit in bds.config...

**Comment by golharam** [comment]
maxThreads?  I see its commented out.  I've now set it to 512.  Let's see
what happens.  This last time it happened when submitting 481 jobs.  How
many threads is BDS creating?

I was just thinking...is the code/class to execute tasks in a cluster is
set up as interface classes, then subclassing them for different types of
clusters should be easy.  I'm not clear if that's what's happening now.  I
see ExecutionerClusterSge among others all extending Executioner.
Executioner manages the cluster (or job submission to a cluster)?

Ryan

**Comment by pcingola** [comment]
For each command executed (such as qstat) I need to fire a thread to 
run the command, a thread to read STDOUT and a thread to read STDERR.
These are short lived, since the threads only lice during the 'qsub' executions, but 
of you are fireing many task this can add up.

If the OS has a low limit, you should tell bds to use less threads (i.e. reduce 
the number in bds.config file)...

**Comment by pcingola** [comment]
The cluster is managed by the cluster management system (e.g. SGE) to 
which I don't have access (it would be dangerous that a program could take 
control over your entire cluster). The Executioner classes dispatch tasks to the 
cluster management system.

**Comment by golharam** [comment]
Ok, I reduced the number to 512.  Once the current run finishes, I'll try
it on the next step.

**Comment by golharam** [comment]
That's what I meant to say, the Executioner class interfaces with/talks to
the cluster management system.

**Comment by golharam** [comment]
that's didn't work either.  I think I want to abandon the SGE Implemention
you are using.  If I can't get this to work, BDS won't work for me.  There
has to be a better/easier way.


00:00:00.692    Config: Attempt to set 'maxThreads' to 32. Too small, using
50 inseatd.

java.lang.RuntimeException: Cannot execute commnads: 'qstat'
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.run(Exec.java:80)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.exec(Exec.java:37)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.CheckTasksRunning.runCommand(CheckTasksRunning.java:226)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.CheckTasksRunning.check(CheckTasksRunning.java:80)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:313)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoop(Executioner.java:426)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:383)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
Exception in thread "Thread-11" java.lang.RuntimeException: Cannot execute
commnads: 'qstat -f -j 1535'
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.run(Exec.java:80)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Exec.exec(Exec.java:37)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.ExecutionerCluster.postMortemInfo(ExecutionerCluster.java:343)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateFinished(Executioner.java:717)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.taskUpdateStates(Executioner.java:778)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.reportsChecksUpdates(Executioner.java:304)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoopAfter(Executioner.java:436)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:397)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
Task failed:
        Program & line     : 'ExomePipeline.bds', line 312
        Task Name          : '40124 indelTargetCreator'
        Task ID            :
'ExomePipeline.bds.20151016_013553_578/task.ExomePipeline.40124_indelTargetCreator.line_312.id_577'
        Task PID           : '1535'
        Task hint          : ' /ngs/apps/jre1.7.0_67/bin/java -Xmx56G -jar
/ngs/apps/GenomeAnalysisTK-2015.1-3-g53415c9/GenomeAnalysisTK.jar \'
        Task resources     : 'cpus: 32  mem: -1.0 B     timeout: 86400
wall-timeout: 86400'
        State              : 'KILLED'
        Dependency state   : 'ERROR'
        Retries available  : '1'
        Input files        :
'[/ngsprojects/NAV1.7_481SampleCohort/analysis/intermediate/40124.dedup.bam]'
        Output files       :
'[/ngsprojects/NAV1.7_481SampleCohort/analysis/intermediate/40124.indelrealigner.list]'
        Script file        :
'/ngsprojects/NAV1.7_481SampleCohort/ExomePipeline.bds.20151016_013553_578/
task.ExomePipeline.40124_indelTargetCreator.line_312.id_577.sh'
        Exit status        : '3'

**Comment by golharam** [comment]
Out of curiosity, why does BDS need to create so many threads?  If its
being submitted to the cluster, you really one need 1 thread monitoring
when jobs complete.  If I have 500 samples in my cohort, and my pipeline
consist of 10 steps, that implies you will need at least 500*10*3 threads?
That seems unreasonable.

**Comment by pcingola** [comment]
Hi Ryan, 
  I suggest that in this "GitHub issue" we focus one solving the bug. If you'd like to talk/discuss 
about bds' architecture, please open another thread (otherwise the discussion quickly 
becomes very difficult to follow).
  I asked before if you could send me the log file, but you still haven't done it and you 
only to send some snippets of the error. Would it be possible to send the whole log output file 
containing both STDOUT and STDERR?  That would be helpful in trying to debug (you 
probably want to send it as an email attachment instead of making it public here).
  One of the key success factors when debugging is being able to replicate the 
error condition. This requires that you send a "minimal script", data and configuration parameters 
that triggers the same error. A minimal script is a script with as few lines of code as possible
and uses very no data files (or little ones that you can attach the email). Could you provide 
this information? 
   I hope you can send me the information because if I don't have it and I'm unable to 
replicate the error condition, I don't quite see how I can solve this bug....

**Comment by golharam** [comment]
How do I create the log file?  I thought I sent it already.  -d?

**Comment by pcingola** [comment]
Looks like I didn't get it.
You can run the minimal script using "bds -v .... > log.txt 2>&1 " 
If possible, running the same using "-d" instead of "-v" is even better.

**Comment by golharam** [comment]
I don't even get a log file.  Here's my command:

bds -v -l -d -s sge -noReport -quiet -c /ngs/apps/bds-0.999k/bds.config
ExomePipeline.bds -readType paired -caller hc -cohort samples.txt
-targetRegionsBedFile targets.sorted.bed -analysisDir analysis

I see a bunch of jobs get submitted to SGE, then I get the following on the
console.  BDS never continues running after that.

java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:713)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runTask(Executioner.java:475)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutionerLoop(Executioner.java:421)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:383)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
java.io.IOException: Cannot run program "qdel": error=11, Resource
temporarily unavailable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
        at java.lang.Runtime.exec(Runtime.java:617)
        at java.lang.Runtime.exec(Runtime.java:485)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.CmdLocal.killBds(CmdLocal.java:149)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.CmdLocal.killCmd(CmdLocal.java:164)
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Cmd.kill(Cmd.java:170)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.kill(Executioner.java:251)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.kill(Executioner.java:228)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:393)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
Caused by: java.io.IOException: error=11, Resource temporarily unavailable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
        ... 9 more
java.io.IOException: Cannot run program "qdel": error=11, Resource
temporarily unavailable
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1041)
        at java.lang.Runtime.exec(Runtime.java:617)
        at java.lang.Runtime.exec(Runtime.java:485)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.CmdLocal.killBds(CmdLocal.java:149)
        at
ca.mcgill.mcb.pcingola.bigDataScript.osCmd.CmdLocal.killCmd(CmdLocal.java:164)
        at ca.mcgill.mcb.pcingola.bigDataScript.osCmd.Cmd.kill(Cmd.java:170)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.kill(Executioner.java:251)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.kill(Executioner.java:228)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.runExecutioner(Executioner.java:393)
        at
ca.mcgill.mcb.pcingola.bigDataScript.executioner.Executioner.run(Executioner.java:367)
Caused by: java.io.IOException: error=11, Resource temporarily unavailable
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:135)
        at java.lang.ProcessImpl.start(ProcessImpl.java:130)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1022)
        ... 9 more

**Comment by pcingola** [comment]
Hi Ryan,
   If you read my previous post, I mention how to create a log file by using 

    bds -v minimal_script.bds > log.txt 2>&1

It looks like you forgot to follow my instructions. If you continue refusing to 
send a minimal script and the log file, I'm sorry but I won't be able 
to help. What I'm asking is not only very simple and reasonable, but 
also the standard when you report a bug for any open source project.
   Yours

       Pablo

**Comment by golharam** [comment]
I've spent the last 2 weeks with this trying to get an analysis done.  I
hope you can understand my frustration.  I've reverted back to using my
shell scripts as they are the most reliable.

The command you want me to run will cause BDS to run locally and not
utilize the cluster.  Is that what you want?  If that's the case, BDS runs
fine when restricted to a single node.

**Comment by pcingola** [comment]
Ryan,
   Let me repeat once more. What I need is: i) a minimal script that I can run in a similar setting and can reproduce the error condition; ii) a log file from your run of that minimal script. If you scripts runs on SGE, then your command line should add the proper "-s sge" options (similarly, I don't expect your script to be named 'minimal_script.bds', it can certainly have another name). I'm giving general guidelines as opposed to specific commands for you to copy&paste because I assume you are knowledgable and intelligent enough to understand this.
   The standard way to capture the STDOUT and STDERR when running a unix command is to use "> log.txt 2>&1". If you don't know how to do this, please get advise from someone who has minimal knowledge of unix command line. Again, the output file does not have to be called 'log.txt', you can use another name.
   The way to create a minimal script is to remove all "non-error causing code" and replace 'task' by simple statements that still capture the error condition.
   I'm not asking for all this just to make your life miserable, I'm doing it in order to be able to replicate the error condition and then debug the problem.
   Yours

     Pablo

**Comment by golharam** [comment]
Attached are the log files from this run:

bds -l -d -v -s sge -c /ngs/apps/bds-0.999k/bds.config ExomePipeline.bds
-readType paired -caller hc -cohort samples.txt -targetRegionsBedFile
targets.sorted.bed -analysisDir analysis >log.txt 2>log.err

followed by a bunch of on the console:
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: retry: Resource temporarily unavailable
-bash: fork: Resource temporarily unavailable

The node becomes unresponsive, and I'm forced to do a cold restart.

I like BDS, despite these issues.  I continue to try to sell it internally
to others in our group.  I think the idea is sound, but BDS needs to be
rearchitected to efficiently use threads.  Opening 3 threads per task is
not reasonable for large-scale analyses.

**Comment by pcingola** [comment]
I received no attachment. Neither the log files, the minimal script, or the data files required to run your script script are in your post. May be it would be easier for you to send me an email.

As I mention before, bds does not open 3 threads per task for the whole time, it only fires them to invoke the qsub/qstat commands which are short lived. If you know a bit about Java internals, you'd remember that this is the correct way to implement it because otherwise you would have deadlocks.

**Comment by golharam** [comment]
There is too much other stuff surrouding my tasks to strip it down anymore,
but this is where its hung up on:
samples is an array of 481 samples.  The rest of the script should be
self-explanatory.

for (string sample : samples) {

    # 7.  Create indel targets
    string indelRealignerTargetsFile =
"$analysisDir/intermediate/$sample.indelrealigner.list"
    task ( indelRealignerTargetsFile <- dedupBamFile, cpus := 8, taskName
:= "$sample indelTargetCreator") {
        sys $javaApp -jar $gatkJar \
                -T RealignerTargetCreator \
                -nt 8 \
                -R $reference \
                -I $dedupBamFile \
                -o $indelRealignerTargetsFile \
            -L $targetRegionsBedFile \
            -allowPotentiallyMisencodedQuals \
            -known $gatk1KGIndels \
            -known $gatkMills
    }

    # 8.  Realign around indels
    task ( realignedBamFile <- [dedupBamFile, indelRealignerTargetsFile],
taskName := "$sample IndelRealigner" ) {
        sys $javaApp -Xmx8G -jar $gatkJar \
            -T IndelRealigner \
            -R $reference \
            -I $dedupBamFile \
            -targetIntervals $indelRealignerTargetsFile \
            -L $targetRegionsBedFile \
            -allowPotentiallyMisencodedQuals \
            -known $gatk1KGIndels \
            -known $gatkMills \
            --disable_auto_index_creation_and_locking_when_reading_rods \
            -o $realignedBamFile
    }
}

**Comment by pcingola** [comment]
I changed some of the code that might be responsible for this bug. 
Since I haven't been able to reproduce the error condition with 
the information you sent me, I'm cannot be sure that this new code 
actually solves the problem, but I'm optimistic.
It would be nice if you could try the latest github version and send 
me some feedback.
Yours

    Pablo

**Comment by golharam** [comment]
I'll check it out when I get a chance.  I think the problem is related to
the # of open file handles allowed (ulimit -n).  Mine is set to 1024.  I
suspect what is happening is when running a very large cohort, BDS (as you
say) is open 3 file handles (stdin, stdout, stderr)? per task.  When qtask
is run, an additional file handles aren't available hence qstat is not
found.

Again, when I get a chance, I'll test your fix.
