### ISSUE TITLE
Read file in string

### ISSUE THREAD

**Issue by apastore** [pcingola/BigDataScript#116]
Hi This is more a question. I am trying to read a each line of a two column file and use each line as a pair of variable.... but without success. there is any methods? thanks!

String content = readFile("test.txt", Charset.defaultCharset());

**Comment by pcingola** [comment]
Closing. It looks like someone already answered your question here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bigdatascript-users/vL8mYK7O0Xg/bz9Yas4DDAAJ
