### ISSUE TITLE
BDS in SSH mode

### ISSUE THREAD

**Issue by jpjais** [pcingola/BigDataScript#118]
Hello Pablo,
I have recently discovered BDS and was very impressed by its possibilities. We have started to migrate one of our workflow in BDS and try to use the SSH remote execution mode for testing (the cluster mode is ok with our scheduler). However the documentation is very limited on the SSH mode specificities, so  a small note on this mode would be useful (i can submit you the different steps we used in our testing configuration). 
We also encountered a null pointer exception in the HostSsh function in SSH mode
(BigDataScript/src/ca/mcgill/mcb/pcingola/bigDataScript/cluster/host/HostSsh.java) which we solved by inverting the health  object  initialization and the setAlive property assignation lines  in the function.
After this patch BDS SSH mode is OK !!!

**Comment by pcingola** [comment]
Hi!
   Keep in mind that ssh is OK for small hacks, but doesn't scale well, so please 
don't base your production pipelines on it. 
   If you could send me your notes I'll add them them to the documentation. Same 
for the code fixing the ssh issue, if you can send the code (or even better, create 
a pull request).
  Yours

    Pablo

**Comment by pcingola** [comment]
Merged your patch which solved this issue.
