### ISSUE TITLE
Problem using -s ssh flag and BDS task

### ISSUE THREAD

**Issue by kohleman** [pcingola/BigDataScript#120]
Calling a BDS script with the -s flag using ssh and define a task in this bds script always fails. Running the script locally (i.e. without the -s flag) runs without problems.

Code from `/links/application/dsu/.bds/bds.config`:

```
ssh.nodes = sbsuser@server.ethz.ch
```

```
> cat /home/sbsuser/bds_scripts/test.bds
for( int i=0 ; i < 10 ; i++ ) task echo Hi $i
```

Running fails:

```
>  /links/application/dsu/.bds/bds -c /links/application/dsu/.bds/bds.config  -s ssh /home/sbsuser/bds_scripts/test.bds
Fatal error: /home/sbsuser/bds_scripts/test.bds, line 7, pos 31. null
test.bds, line 7 :  for( int i=0 ; i < 10 ; i++ ) task echo Hi $i

Creating checkpoint file '/home/sbsuser/bds_scripts/test.bds.line_7.chp'
```

Locally:

```
>  /links/application/dsu/.bds/bds -c /links/application/dsu/.bds/bds.config  /home/sbsuser/bds_scripts/test.bds
Hi 7
Hi 4
Hi 1
Hi 6
Hi 2
Hi 3
Hi 5
Hi 0
Hi 8
Hi 9
```

I have no idea why this is failing. Could someone help me out?

**Comment by pcingola** [comment]
Here are a few tips that might be useful:
  i) Can you ssh into the other machine directly? (i.e. no password prompt). A simple 
     test would be to see if this works OK

     ssh sbsuser@server.ethz.ch ls

   ii) Is bds installed? Is it in your PATH? A quick test, this command should work and show you the standard bds help page:

     ssh sbsuser@server.ethz.ch bds

   iii) The common assumption is that the underlying file system is shared (e.g. NFS) so scripts 
        executed using bds can see you data (bds "communicates" via the shared file system). Is 
       this correctly exported and shared amongst all the computers you are using? (in this case 
       seems to be only one)

   iv) Do you get the same error if you use your localhost as your "remote" computer. Note that this
        assumes that you can do password-less ssh to your own computer, as in i).

I hope this helps

    Pablo

**Comment by kohleman** [comment]
Hi Pablo,
thanks for these hints. All points are fine and work without problems. I got it working without the -s flag from bds. I call bds directly via ssh from python:
```
command = ["ssh", "sbsuser@server.ethz.ch",  bdsBinary, "-c", configFile, bdsScript ]
```
instead of 
```
command = [bdsBinary, "-c", configFile, "-s", "ssh", bdsScript]
```

**Comment by pcingola** [comment]
First, you should run bds from the command line when you are debugging.

Second, those two commands are completely different. The first command 
runs "ssh" to log into a remote computer, then runs bds in the remote computer 
as a local process. The second command runs bds in the local computer and 
tells it to use a farm of nodes for processing (the way to access these nodes 
to establish the process is via "ssh"). Clearly very different things. Why makes 
me wonder: what exactly do you want to do?

**Comment by pcingola** [comment]
Closing old issues, feel free to re-open.
