### ISSUE TITLE
Ability to set cpusLocal for use of BDS on shared systems?

### ISSUE THREAD

**Issue by jasonsydes** [pcingola/BigDataScript#121]
Hi BDS!  I was curious if it might be possible for BDS to allow the setting of int cpusLocal?  There are machines we have access to in which a small group of users occasionally use the computational resources.  However, they often don't use the entire machine, and it would be nice to be able to grab those 10 or 20 cores for something really quick, without having to limit my list of input files or adjust my cpus := variable within my scripts.  

Currently, as I understand it, BDS will attempt to take all available cores.  If I could set int cpusLocal either within my script or from the command line, I could throttle my use of a given machine.

This is a pretty common use case for our lab's workload.  Often you have something semi-low priority that you just want to spin up in the background, but not consume the entire machine, so that others can use it in the meantime.

If this is already in BDS, great!  If it's not, and there's time to implement it, it would be great to have some way to throttle BDS's use of cores.

Thank you for your time!

**Comment by pcingola** [comment]
I've submitted a patch and now cpusLocal is a global variable instead of a 
constant. Furthermore you can now set global variables directly from the command 
line using the automatic command line parsing mechanism (i.e. as you can do 
with program's variables):
E.g:

    $ cat z.bds
    #!/usr/bin/env bds
    print "cpus : $cpus\ncpusLocal: $cpusLocal\n"

    $ ./z.bds -cpusLocal 3
    cpus : 1
    cpusLocal: 3

**Comment by pcingola** [comment]
I think this new code solves the issue.

**Comment by jasonsydes** [comment]
Thank you so much for the change!  And so quickly too! This will be very helpful. Thanks again!!

**Comment by jasonsydes** [comment]
So I don't lose track of it, here's the commit referenced that fixed this feature request: 1575e011cab73f57db2c0e7ee2f0df34d6dbcfd1
