### ISSUE TITLE
Global BDS_HOME for libs

### ISSUE THREAD

**Issue by zfo** [pcingola/BigDataScript#123]
Hey I hacked together an [Arch package](https://aur.archlinux.org/packages/bigdatascript-git/) for your great lib. However when bundling this as a package I realized that `BDS_HOME` can be either `/usr/local/bds` or `~/.bds`, but if run as a user the first is always used.

Imho it would be nice to use `/usr/local/bds` and thus use globally installed libs like other languages and  use the local directory additionally, e.g. for user installed libs or config.

**Comment by pcingola** [comment]
Closing old issues, feel free to re-open.
