### ISSUE TITLE
Using SLURM in BDS?

### ISSUE THREAD

**Issue by riyuebao** [pcingola/BigDataScript#124]
Hi Pablo,

We have been using BDS on AWS EC2 with SGE and it worked perfectly. We recently started to work on a different HPC and it only implements SLURM (https://computing.llnl.gov/linux/slurm/). I was wondering is it possible to add SLURM support in BDS, or is there any way to twist the commands a bit to make BDS work with SLURM? 

Thank you very much!

Best,
Riyue (Sunny)
## 

Riyue Bao, Ph.D.
Bioinformatician
Center for Research Informatics | Biological Sciences Division
The University of Chicago

**Comment by pcingola** [comment]
Hi Riyue,
   There is a mechanism to support clusters via "generic cluster" mechanism. You simply 
have to write a couple of scripts to submit, cancel and query running tasks in the cluster.
You can find some information in the "Generic cluster" section of the online documentation 
and in the default config file. 
  A better option would be to write an Executioner for SLURM by extending the Java classes for 
other clusters. This is slightly more involved but I can provide some guidance if you are willing 
to write it.
   

    Pablo

**Comment by riyuebao** [comment]
Hi Pablo,

Thank you! The generic cluster mechanism looks awesome (sorry I missed it before). I will prepare scripts similar to those in the clusterGeneric directory and try to make it work. I may come back with questions if you don't mind.

I would love to contribute but last time I touched Java was back in class =/ But I do know someone who is willing to help write up the Executioner. I would appreciate your guidance on where to start, and we will work on it in the next couple of weeks.

Thank you again for your time and help.

Best,
Riyue

**Comment by pcingola** [comment]
Try the script for generic cluster. Based on that, the executioner should be not so difficult by copying the code from other executioners (e.g. SGE).

**Comment by leepc12** [comment]
I have my own implementation for SLURM using a generic cluster. I would like to share it with you.

Usage: `bds -s generic your_code.bds ...`

bds.config
```
# default system (local, sge, ...)
system = local

# shell env.
taskShell = /bin/bash -e
sysShell = /bin/bash -e -c

# regex to get pid
#pidRegex = "Your job (\\S+)"
pidRegex = "(\\d+$)"

# checkpoint disabled, show full commands/stderr/stdout on task, filter out commands including "export" from task hint
disableCheckpoint = true
taskMaxHintLen = 300
showTaskCode = true
tailLines = 100000000
filterOutTaskHint = export
clusterPostMortemDisabled = true        # prevent error on scg3/4

# SGE
sge.pe = shm
sge.mem = h_vmem
sge.timeout = h_rt

# SLURM (using generic cluster)
clusterGenericRun = ~/.bds/clusterGeneric/run.pl
clusterGenericKill = ~/.bds/clusterGeneric/kill.pl
clusterGenericStat = ~/.bds/clusterGeneric/stat.pl
clusterGenericPostMortemInfo = ~/.bds/clusterGeneric/postMortemInfo.pl
```
run.pl
```
#!/usr/bin/perl

use POSIX;

die "Error: Missing arguments.\nUsage: run.pl timeout cpus mem queue saveStdout saveStderr cmd arg1 ... argN\n" if $#ARGV < 6 ;

$timeout = shift @ARGV;
$cpus = shift @ARGV;
$mem = shift @ARGV;
$queue = shift @ARGV;
$saveStdout = shift @ARGV;
$saveStderr = shift @ARGV;
$cmd = join(' ', @ARGV);

$qsub = "sbatch --export=ALL ";
$qsub .= "-n 1 --ntasks-per-node=1 --cpus-per-task=$cpus " if( $cpus > 0 );
if( $mem > 0 ) {
        $mem = ceil($mem/1000000); # MB
        $qsub .= "--mem-per-cpu $mem ";
}
if( $timeout > 0 ) {
        $timeout = ceil($timeout/60); # minute
        $qsub .= "-t $timeout ";
}

$pid = open QSUB, " | $qsub";
die "Cannot run command '$qsub'\n" if ! kill(0, $pid); # Check that process exists
print QSUB "#!/bin/sh \n";      # SLURM sbatch needs this shebang...
print QSUB "$cmd\n";            # Send cluster's task via qsub's STDIN
close QSUB;

exit(0);
```
#!/usr/bin/perl

$exitCode = system "squeue";

# OK
exit($exitCode);
```
kill.pl
```
#!/usr/bin/perl

die "Error: Missing arguments.\nUsage: kill.pl jobId\n" if $#ARGV < 0 ;
#$jobId = shift @ARGV;
$jobId = join(' ', @ARGV);

$exitCode = system "scancel $jobId";

# OK
exit($exitCode);
```

**Comment by riyuebao** [comment]
Thanks @leepc12!!

**Comment by pansapiens** [comment]
There are now SLURM wrapper scripts in the master branch (as of #158) in case anyone missed it: https://github.com/pcingola/BigDataScript/tree/master/config/clusterGeneric_SLURM

Might be time to close this issue ?

**Comment by pcingola** [comment]
Closing old issues, feel free to re-open.
