### ISSUE TITLE
Using bash option (/bin/bash -o) in bds.config

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#132]
Here is my bds.config.
```
taskShell = /bin/bash -e -o pipefail
sysShell = /bin/bash -e -o pipefail -c
```

When I run any test bds file, I got the following error:
```
/bin/bash: line 0: /bin/bash: /mnt/data/scratch/leepc12/run/new_code_test/atac_Hardison/ENCSR428BSK/test.bds.20160524_233517_955/task.test.line_9.id_1.sh: invalid option name
```

How can I use -o pipefail in bds.config? This option is very important because my pipeline has lots of UNIX pipe stream. Without -o pipefail, BDS cannot catch non-zero exit code in a pipe.

**Comment by pcingola** [comment]
This seems to work OK for me:

First I create a simple program having a task with a pipe that should fail

    $ cat z.bds
    task  ls zxzx | echo hi    # Note: File 'zxzx' does not exists, so this task will fail is '-o pipefail'

I run it first without any change in the config and it executes OK:

    $ bds z.bds
    hi
    ls: zxzx: No such file or directory
    $

Now I add "-o pipefail"

    $ echo "taskShell = /bin/bash -e -o pipefail" >> ~/.bds/bds.config

And I re-execute (note that I use '-log' in order to examine the shell file afterwards):

    $ bds -log z.bds
    hi
    ls: zxzx: No such file or directory
    Task failed:
    	Program & line     : 'z.bds', line 1
	Task Name          : ''
	Task ID            : 'z.bds.20160606_223827_994/task.z.line_1.id_1'
	Task PID           : '600'
	Task hint          : 'ls zxzx | echo hi'
	Task resources     : 'cpus: 1	mem: -1.0 B	timeout: 86400	wall-timeout: 86400'
	State              : 'ERROR'
	Dependency state   : 'ERROR'
	Retries available  : '1'
	Input files        : '[]'
	Output files       : '[]'
	Script file        : '/Users/pcingola/z.bds.20160606_223827_994/task.z.line_1.id_1.sh'
	Exit status        : '1'
	StdErr (10 lines)  :
		ls: zxzx: No such file or directory
	StdOut (10 lines)  :
		hi

Looking at the shell file, you can see:

    $ cat /Users/pcingola/z.bds.20160606_223827_994/task.z.line_1.id_1.sh
    #!/bin/bash -e -o pipefail
    
    cd '/Users/pcingola'
    ls zxzx | echo hi    

So it seems to be working OK.

**Comment by leepc12** [comment]
I think this depends on server settings. Your example does not work on my cluster. Still getting the same error.

I added `sys set -o pipefail` at the beginning of all tasks and it works fine.

**Comment by pcingola** [comment]
May be "/bin/sh" doesn't always point to bash? Some Linux distros have 'dash' instead, I'm not sure if this makes a difference.

Another option would be to write your config like this:

    taskShell = /bin/bash -e \n set -o pipefail

In that case the "set -o pipefail" will be added to all your tasks
e.g.:
    $ cat z.bds
    task echo hi

Then we execute:
    $ bds -log z.bds
    hi

As you can see the shell script has the desired 'set' command:

    $ cat z.bds.20160610_172312_885/task.z.line_1.id_1.sh 
    #!/bin/bash -e 
    set -o pipefail
    cd '/home/pcingola'
    echo hi
