### ISSUE TITLE
high java memory usage 250~500MB and # threads per pipeline

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#133]
I got a similar situation described in https://github.com/pcingola/BigDataScript/issues/114

I am working on a cluster with 30 nodes (each node has 40 cpus and memory of 250GB) and it's controlled by SGE.

Each BDS java instance took 500MB with SGE.

```
leepc12  101998  4.9  0.7 10420500 474908 pts/100 Sl+ 13:30   0:15 java -Xmx2G -Djava.library.path=/home/leepc12/.bds/lib -cp /home/leepc12/.bds/bds ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript
```

On other clusters without SGE, I can run pipelines locally without `-s sge` option. For such case, Each BDS java instance took 250MB without SGE.

```
leepc12  24659  0.1  0.0 968752 201304 pts/21  Sl+  01:05   1:06 java -Xmx2G -Djava.library.path=/usr/bin/lib -cp /usr/bin/bds ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript
```

Each BDS instance has 20~30 threads.

```
$ ps huH p 24659 | wc -l
20
```

I need to run more than 70 BDS pipelines (https://github.com/kundajelab/TF_chipseq_pipeline) at the same time, but each BDS instance takes more than 20~30 threads so it quickly reaches server limit 1024 (`ulimit -u`). 

```
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
...
```

Moreover, the SGE cluster has a login node which has small memory of 10GB and this node is where I execute BDS commands. 20 BDS instances take 10GB and this results in the following error:

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
```

Why does BDS take so much memory and many threads even though it just schedules tasks and compare file timestamps? Is there any way to reduce it?

On both servers, I use `export _JAVA_OPTIONS="-Xms128M -Xmx1024M -XX:ParallelGCThreads=1"` I am also using `maxThreads=50` in `bds.config`.

**Comment by pcingola** [comment]
Closing old issues, feel free to re-open.
