### ISSUE TITLE
`string.dirPath()` returns a list when string is empty

### ISSUE THREAD

**Issue by serine** [pcingola/BigDataScript#136]
Hi Pablo, 

When I run this code 

```
string check

string tt = check.dirPath()

print("$tt \n")
```

```
bds z.bds -check /file/path/ 
```

it works correctly, but if I run without anything

`bds z.bds` then it lists root directory 

```
[/bin, /boot, /dev, /etc, /home,...
```

_output is truncated by me_ 

I'm not sure if that is how it suppose to be ..

Thanks

**Comment by serine** [comment]
It would be nice if it returned an empty list if no `string check` is empty

**Comment by serine** [comment]
Sorry to saturate you with extra information, but its clear to me know what was going with my bds script. It was getting hung and wouldn't exit.. I couldn't figure out why and tracked down to this function

```
string[] getFqFiles(string fqDir, string extn) {
    if( ( (!align.isEmpty()) || (fastqc) ) && (fqDir.isEmpty()) ) error "Usage: -fqDir /path/to/your/FASTQ/files"
    string[] fqFiles
    // go through each file and check if its file or directory
    for(string dir : fqDir.dirPath()){
        print("$dir \n")
        bool chkDir = dir.isDir()
        // check if dir is directory call getFqFiles on it
        if(chkDir) fqFiles += getFqFiles(dir, extn)
        // otherwise check if dir is FASTQ file and append it to the fqFiles
        else {
            bool fqFile = dir.endsWith(extn)
            if(fqFile) fqFiles.add(dir)
        }
    }
    // return fqFiles array
    return fqFiles
}
```

I assumed if `fqDir` isn't specified by user then it'll be empty and `fqDir.dirPath` would return an empty list and the `for loop` inside the function would never happened - instead it was recursively finding ALL FASTAQ files on the server...! that's alot of FASTAQ :smile: 

Thanks

**Comment by serine** [comment]
@pcingola just gonna poke you again about this issue. It hasn't been a problem for me, but I want to close this issue, but not sure if this is a feature or a bug :D ?

```
[m3-login1]~$ cat z.bds 
string check

string[] tt = check.dirPath()

print("$tt \n")

[m3-login1]~$ bds z.bds 
[/.autorelabel, /1, /bin, /boot, /dev, /etc, /home, /lib, /lib64, /local_home, /lost+found, /media, /mnt, /opt, /proc, /projects, /root, /run, /sbin, /scratch, /srv, /sys, /tmp, /usr, /var] 

[m3-login1]~$ bds
Bds 2.0rc10 (build 2018-07-05 09:58), by Pablo Cingolani

Error: Missing program file name.
Usage: Bds [options] file.bds
```

**Comment by pcingola** [comment]
Closing old issues, feel free to re-open.
