### ISSUE TITLE
Return behavior/error messaging odd (though I can't prove it's incorrect)

### ISSUE THREAD

**Issue by EamonnMR** [pcingola/BigDataScript#143]
Return's behavior is consistent if you treat it as an expression/function that itself returns void. But weird.

```
void no_compile(){
    return return false
}

void compile() {
    return return '/'.chdir()
}
```

A non-void function with no return statement gets a warning, but a void function with a void return statement, or any function with multiple return statements in the same statement do not get warnings.

Interestingly, if you try to put multiple returns into a void array constructor, it also won't compile:

```
void print_foo(){
    print 'foo'
}

void print_bar(){
    print 'bar'
}

bool test_return(){
    void[] array = [return print_foo(), return print_bar()]
}
```

I also tried chaining returns with &&/||. Tends to give "cannot find viable alternative" errors.

**Comment by pcingola** [comment]
Empty `return` returns void, so it makes sense that `return return` works OK but the others don't.

The following code compiles without errors or warnings in C:

    void f() { return; }
    void g() { return f(); }

And getting `f()` inlined in `g()` would be (conceptually) the same as `return return`.

That being said, bds' compilation error should be more helpful.

**Comment by EamonnMR** [comment]
And there are definitely no ways to chain two void statements together such that we might encounter something that might produce hard-to-predict side effects such at this:

```[return f(), return g()]  #  I could not get anything of this nature to compile, but some might exist```

**Comment by pcingola** [comment]
Closing old issues, feel free to re-open.
