### ISSUE TITLE
help with ignored info in bds.config and ignored -s  and -q options in bds

### ISSUE THREAD

**Issue by e-manduchi** [pcingola/BigDataScript#151]
Hello, I would like to try your pipeline. I don't have administrative privileges on our cluster, so I've installed it in a directory where I have permissions.
I edited the bds.config file (which is in the same directory as bds)  to have:

system = sge
queue = all.q
sge.pe = smp

Then I prepared an atac.config file for a particular run I want to do, where I set nth=6. When I run

bds atac.bds atac.config

no 'qsub' is occurring; the programs run on the master node, and the log has

== cluster/system info
Walltime (general)              : 5h50m
Max. memory (general)           : 7G
Force to use a system           : local
Process priority (niceness)     : 0
Retiral for failed tasks        : 0
Submit tasks to a cluster queue :
Unlimited cluster mem./walltime : false
====

which indicates that it's not seeing the 'system=sge' in bds.config nor the 'queue=all.q'
I've also tried to run with bds -s sge -q all.q and the same occurs. The only way to have it issue qsub is if I add the line 'use_system=sge' to the atac.config file:

== cluster/system info
Walltime (general)              : 5h50m
Max. memory (general)           : 7G
Force to use a system           : sge
Process priority (niceness)     : 0
Retiral for failed tasks        : 0
Submit tasks to a cluster queue :
Unlimited cluster mem./walltime : false
===

However the queue is still not recognized, but most importantly since sge.pe=smp is not seen I get the error 
Error message      : 'Unable to run job: denied: parallel environment "shm" does not exist

Can you advice?
Thank you for your attention.

**Comment by e-manduchi** [comment]
Update: I now see that I have to explicitly provide the -c option when I run bds to indicate the location of the config file as it's not looking into the same directory of bds but the default behavior is to look into $HOME/bds/

**Comment by pcingola** [comment]
OK.
