### ISSUE TITLE
broken link to paper on website

### ISSUE THREAD

**Issue by 0xAF1F** [pcingola/BigDataScript#152]
On http://pcingola.github.io/BigDataScript/
The link to the paper in the following sentence is broken.
"Read our paper for a detailed introduction. If you use bds in an academic environment, please cite our work. "

**Comment by pcingola** [comment]
Fixed. Thank you for the heads-up!

**Comment by 0xAF1F** [comment]
The link is also broken on http://pcingola.github.io/BigDataScript/bigDataScript_manual.html
You might like to link to the DOI resolver (<https://doi.org/10.1093/bioinformatics/btu595>); that shouldn't change and people might not like to download the PDF right away.

**Comment by pcingola** [comment]
Fixed. Thank you for your suggestion.
