### ISSUE TITLE
release binaries committed to repository

### ISSUE THREAD

**Issue by 0xAF1F** [pcingola/BigDataScript#153]
I'm a bit confused why you've stopped making tagged releases with the binaries attached and instead just commit them with the source code. It would be helpful for us to know when there is a new release to update to if the release tags could be maintained. And it's a bit of an abuse of Git to commit the binary together with the source code.

**Comment by pcingola** [comment]
Thank you for your comments. I'll try to change the release process as suggested.

**Comment by 0xAF1F** [comment]
Thanks!

Do you still consider this program experimental (it says so on the website) or is it ready for production use? I got a user request to install it on our cluster, but I wouldn't do a central installation if it's experimental.

**Comment by pcingola** [comment]
The program has been used in production environments for years by several
people/companies.
I say "experimental use at your own risk" simply because I don't want some
idiot to sue me if they hit a bug...

**Comment by 0xAF1F** [comment]
Ah, ok. Thank you for clarifying that.
