### ISSUE TITLE
prerequisite ignored?

### ISSUE THREAD

**Issue by 0xAF1F** [pcingola/BigDataScript#154]
Can you help me to see if I just misunderstood something. I ran test_18 having forgotten to create `in.txt` beforehand, but it still worked. If I understand the file correctly, it should have failed because of the absence of `in.txt`:

```
$ wget http://pcingola.github.io/BigDataScript/bds/test_18.bds
...
$ cat test_18.bds 
#!/usr/bin/env bds

in   := 'in.txt'
mid1 := 'mid1.txt'
mid2 := 'mid2.txt'
out  := 'out.txt'

stime := 3

# Dependencies: There is no need declare them in order
dep( out <- mid2 )     sys echo $mid2 > $out  ; echo OUT   ; sleep 1
dep( mid2 <- mid1 )    sys echo $mid1 > $mid2 ; echo MID2  ; sleep 1
dep( mid1 <- in )	   sys echo $in   > $mid1 ; echo MID1  ; sleep 1

goal out
$ ls
test_18.bds
$ chmod +x test_18.bds
$ ./test_18.bds
MID1
MID2
OUT
$ ls
mid1.txt  mid2.txt  out.txt  test_18.bds
$ bds -version
Bds 0.99999l (build 2017-05-12 14:34), by Pablo Cingolani
```

This is with no configuration file in ~/.bds, so I expect it to be using all default settings.

**Comment by pcingola** [comment]
The dependency operator first checks whether the left-hand sides exists ('mid1.txt')  if the file doesn't exist, 
the task is triggered regardless of the right-hand existence or creation time.
I hope this clarifies.

**Comment by pcingola** [comment]
Just to clarify, the same happens if any left-hand side file has zero length or is an empty directory.

**Comment by 0xAF1F** [comment]
Oh, ok, thank you. I see you also have this explained in https://pcingola.github.io/BigDataScript/bigDataScript_manual.html#dep
I must have just gotten confused because it's not what I'm used to.
