### ISSUE TITLE
string.split()

### ISSUE THREAD

**Issue by JurijsNazarovs** [pcingola/BigDataScript#155]
Hello,

I have a question about string.split(), if behavior below is expected one or not. The output of 

a := "tag23"
b := a.split("[1-9][0-9]*")
bSize := b.size()
print "b is $b\n"
print "b size is $bSize\n"

is:

b is [tag, ]
b size is 2

I am not sure if this is expected behavior, but I think that in some version before it worked differently. The same code would return me:
b is [tag]
b size is 1

**Comment by pcingola** [comment]
Yes, this is indeed the expected behavior.
The 'split' method implementation is done invoking java's `String.split(regex, -1)` (i.e. the 'limit' parameter is negative, which means that it doesn't discard trailing empty strings.
