### ISSUE TITLE
Web site manual page problems

### ISSUE THREAD

**Issue by tedtoal** [pcingola/BigDataScript#156]
Minor (some picky) improvements for the manual web page.  Fixing these will make it look more professional.

Typos:
"varaible"
"commnad"
"positon"
"srting"
"inetrval"
"rootof"
"executng"
"preivous"
"necesary"
"Exmple"
"resourcerces"
"charaters"
"experession"
"mutiple"
"avilable"
"leters"
"checkpopint"
"varialbe"
"overriden"
"peole"
"appropiate "
"Simetime"
"usualy"
"supproted"
"spce"

Fixed or better wording:

"Upload data from URL" -> "Upload data to URL"
"form the list" -> "from the list"
"bo doing" -> "by doing"
"hashes" -> "dictionaries" (or say "maps, dictionaries, and hashes are the same thing")
"cubic root" -> "cube root"
"trigonometric hyperbolic" -> "hyperbolic"
"the both tasks are" -> "both tasks are"
"sintactic" -> "syntactic"
"sintatic" -> "syntactic"
"common, that we allow" -> "common that we allow"
"executing task in" -> "executing tasks in"
"second task, uses" -> "second task uses"
"to declare variable" -> "to declare variables"
"convinience" -> "convenience"
"convinient" -> "convenient"
"execution Mesos" -> "execution in Mesos"
"use a wait statements" -> "use a wait statement"
"ony used" -> "only used"
"execution of task can" -> "execution of tasks can"
"file does not exits" -> "file does not exist"
"...once, you can do this by passing a list, instead of a string to" ->
    "...once.  You can do this by passing a list, instead of a string, to"
"with no arguments, would wait" -> "with no arguments would wait"
"trigered" -> "triggered"
"a par it is a" -> "a par is a"
"An automatic command line 'help' for your scripts can be created automatically" ->
    "Command line 'help' for your scripts can be created automatically"
"Note that by default variables are sorted" -> "By default variables are sorted"
"it's type" => "its type"
"usefull" -> "useful"
"mundane, boring but" -> "mundane and boring, but"
"logging, that's why" -> "logging. That's why"
"kill all pending task." -> "kill all pending tasks."
"Sometimes cluster fails" -> "Sometimes clusters fail"
"is unable to detect a failure" -> "is unable to detect"
"task disappear" -> "tasks disappear"
"If any tasks" -> "If any task"
"Running the command line without any arguments, shows a help message" ->
    "Running the bds command without any arguments shows a help message"
"config's file dir" -> "config file's dir"
"Tasks required CPUs" -> "Task's required CPUs"
"columns may exists" -> "columns may exist"
"(e.g. qstat). One per" -> "(e.g. qstat), one per"
"and it added" -> "and is added"

Descriptions are reversed for: assert(string expected, string result)  
and:  assert(string msg, string expected, string result)

nextAfter() and nextUp(): it is unclear what "adjacent" means

"Returns the size of an ulp of the argument" - what is an "ulp"?

"Note that bds interpolates variable $i" - Unclear what is meant by "interpolates"

Out of order at top of table instead of within table: "Do not create any report (neither HTML nor YAML). Do not create HTML report."

**Comment by pcingola** [comment]
Hi!
I've fixed all the typos as you suggested. Thank you!
Apologies for not getting back to you earlier, I somehow missed the Github alert.
Thank you for your detailed spelling corrections!

**Comment by pcingola** [comment]
Closing. Uploaded page with typos fixed.
Thank you!
