### ISSUE TITLE
printHelp() and printErr() results in Unimplemented. This method should never be invoked!

### ISSUE THREAD

**Issue by serine** [pcingola/BigDataScript#165]
@pcingola I'm having issues with `printHelp()` and `printErr()` function. 

Working off master, this is latest commit on my copy d6747cc

I don't actually use `printErr()` but it is resulting in the same error. I've attached [log file](https://github.com/pcingola/BigDataScript/files/2047081/t.log)

```
[bioinformatics2]~/gitrepos/BigDataScript (master)$ ~/.bds/bds -d t.bds > t.log 2>&1
[bioinformatics2]~/gitrepos/BigDataScript (master)$ cat t.bds
printErr(" ")
```

Thanks

**Comment by serine** [comment]
Just to add a quick comment, might not be directly related to the problem. 

The bds that I have currently installed b2f27b6 `printHelp()` exi

**Comment by serine** [comment]
That specific issue has been fixed! Thanks. 

but something else poped up
looking into it now, but something about this line in my code

```
        dep(cov, bigWigFile <- [bamFile, chromSizes, fastaRef], canFail := true, taskName := "Getting coverage files in bigWig for $bamFile", tmp := "$bedGraphFile.tmp") {
```

```
[bioinformatics2]~/gitrepos/RNAsik-pipe (master)$ ~/.bds/bds src/RNAsik.bds
Compiler messages:
ERROR [ file 'src/sikCoverage.bds', line 31 ] : Expression 'bedGraphFile' is not an object
ERROR [ file 'src/sikCoverage.bds', line 31 ] : Class 'string' does not have memeber 'tmp'
ERROR [ file 'src/sikHisat2.bds', line 28 ] :   Expression 'i' is not an object
ERROR [ file 'src/sikHisat2.bds', line 28 ] :   Class 'int' does not have memeber 'ht2'
ERROR [ file 'src/sikHisat2.bds', line 67 ] :   Expression 'i' is not an object
ERROR [ file 'src/sikHisat2.bds', line 67 ] :   Class 'int' does not have memeber 'ht2'
```

**Comment by serine** [comment]
this function https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe/blob/5137e74ffa9cfb2a54ec428ecabc7f13baf40233/src/sikCoverage.bds#L31

**Comment by serine** [comment]
So just to add and simplify the problem, this is a problem 

```
[bioinformatics2]~/gitrepos/BigDataScript (master)$ ~/.bds/bds -d t.bds
Config.findConfigFile(209):     Trying config file './bds.config'
Config.findConfigFile(209):     Trying config file '/mnt/ceph/mbp/servers/bioinformatics-platform/home/kirill/.bds/bds.config'
00:00:00.000    Bds 2.0rc7 (build 2018-05-30 10:32), by Pablo Cingolani
00:00:00.046    BdsRun: Initialize standard libraries.
00:00:00.122    BdsRun: Native library: 70
00:00:00.161    BdsRun: Native library: 56
00:00:00.170    Parsing
Compiler messages:
ERROR [ file 't.bds', line 2 ] :        Expression 'tmp' is not an object
ERROR [ file 't.bds', line 2 ] :        Class 'string' does not have memeber 'txt'

Compiler messages:
ERROR [ file 't.bds', line 2 ] :        Expression 'tmp' is not an object
ERROR [ file 't.bds', line 2 ] :        Class 'string' does not have memeber 'txt'

00:00:00.727    Finished. Exit code: 1
BdsRun.run(361):        Finished: Killinig executioners
[bioinformatics2]~/gitrepos/BigDataScript (master)$ cat t.bds
string tmp = "Hello"
print("$tmp.txt \n")
```

And if I put a space between `$tmp` and `.txt` like this `print("$tmp .txt \n")` everything works ok

**Comment by pcingola** [comment]
Yes, this is actually a new feature (not a bug), but I understand the transition can be annoying...

Bds 2.0 has objects (you can define a "class"). In order to access an object's fields, you use the notation `obj.field`, as in many other programming languages. So when interpolating `"$tmp.txt"` is interpreted as field 'txt' in object 'tmp'. But 'tmp' is not an object, it's a string and that's why the error message.

A solution is to change from `"$tmp.txt"` to `"$tmp\.txt"` (notice the added backslash before the dot).

Does it make sense?

**Comment by serine** [comment]
Awesome, thanks heaps
