### ISSUE TITLE
Add try / catch / finally statements

### ISSUE THREAD

**Issue by pcingola** [pcingola/BigDataScript#171]
There is no proper error handling, we need `try` / `catch` / `finally`

**Comment by ramasCoder** [comment]
Do you need it for entire project or specific files ?

**Comment by pcingola** [comment]
Implemented in bds 2.0

**Comment by juancrescente** [comment]
documentation for this?

**Comment by pcingola** [comment]
...mmm... you are right, docs are missing, I'll try to add them soon.
