### ISSUE TITLE
remote_*.bds.* directories in project root added in error ?

### ISSUE THREAD

**Issue by pansapiens** [pcingola/BigDataScript#182]
There are a bunch of `remote_*.bds.*` directories in the project root on `master` - these seem out of place / messy. Were they added in error, or as these supposed to be there ?

**Comment by pcingola** [comment]
Thank you for opening an issue.
Can you spare some more details? Where are you getting these dirs and where should they be?
Do you have a simple / minimal code showing the problem? It would be great for debugging...

**Comment by pansapiens** [comment]
These are directories in the git repo, right here. eg https://github.com/pcingola/BigDataScript/tree/master/remote_03.bds.20190430_223219_877

Maybe they are meant to be here and I don't understand their purpose, but they look like the result of test runs that were committed in error.

**Comment by pcingola** [comment]
Yes, those are tmp files from test cases runs. I've removed them. Thank you for the heads-up
