### ISSUE TITLE
BDS LSF Support

### ISSUE THREAD

**Issue by jhooge** [pcingola/BigDataScript#33]
Hello Pablo,

I'm working as a Bioinformatician and Bayer Healthcare and I'm responsible for the development of our NGS pipelines. Currently I'm using bpipe, however due to its code intransparency I'm a bit unhappy with it and I'm currently looking into alternatives. We're using an LSF job scheduler on our HPC and BDS seems a viable alternative to our current pipeline solution, that is, if it did support LSF. However, skimming through your documentation, this doesn't seem to be the case. Are you planning to provide LSF support in the future?

Kind regards,
Jens

**Comment by mxqian** [comment]
I am interested in using this on LSF.  What's going on about this now?  Has LSF been supported yet?  Thanks.

**Comment by pcingola** [comment]
I don't have access to an LSF cluster, but you should be able to easily adapt bds for any cluster type using the "Generic cluster" hooks.

**Comment by mxqian** [comment]
I'm trying to understand and do it. 
So, there were 4 perl scripts/settings:
clusterGenericRun = ~/.bds/clusterGeneric/run.pl
clusterGenericKill = ~/.bds/clusterGeneric/kill.pl
clusterGenericStat = ~/.bds/clusterGeneric/stat.pl
clusterGenericPostMortemInfo = ~/.bds/clusterGeneric/postMortemInfo.pl

One way is to replace these files according to the cluster (e.g. LFS/bsub). And then call "bds -s generic". Right?

Is it possible to rename the variable and folder name? For example:
clusterLFSRun =~/.bds/clusterLFS/run.pl
And then how let the "-s" to recognize the option?  

Many thanks in advance.

**Comment by pcingola** [comment]
Exactly.
You can other scripts, just change the bds.config file accordingly. Look for 
the entries: clusterGenericRun, clusterGenericKill, clusterGenericStat and clusterGenericPostMortemInfo. In the example bds.config there is a brief 
description for each. I'm assuming it should be straightforward to 
implement, although I don't use LSF.

It is not possible to rename at the moment. But if you send me your 
implementation, I'll add them using that name and add the "-s lsf" option 
for it.

**Comment by rfarouni** [comment]
Hi,
I have modified the files to run on LSF. Here is what I have:

For kill.pl
```
#!/usr/bin/perl
#---
# Parse command line arguments
#---
die "Error: Missing arguments.\nUsage: kill.pl jobId\n" if $#ARGV < 0 ;
#$jobId = shift @ARGV;
$jobId = join(' ', @ARGV);

# Execute cluster command to kill task
#---
$exitCode = system "bkill $jobId";

# OK
exit($exitCode);
```
for run.pl

```
#!/usr/bin/perl

use POSIX;

die "Error: Missing arguments.\nUsage: run.pl timeout cpus mem queue saveStdout saveStderr cmd arg1 ... argN\n" if $#ARGV < 6 ;

$timeout = shift @ARGV;
$cpus = shift @ARGV;
$mem = shift @ARGV;
$queue = shift @ARGV;
$saveStdout = shift @ARGV;
$saveStderr = shift @ARGV;
$cmd = join(' ', @ARGV);

$qsub = "bsub ";

if( $cpus > 0 ) {
	$qsub .= "-n $cpus";
}


if( $mem > 0 ) {
	$mem = ceil($mem/1000000); # MB
	$qsub .= "-M $mem ";
}
if( $timeout > 0 ) {
	$timeout = ceil($timeout/60); # minute
	$qsub .= "-W $timeout ";
}
if ( $queue ne "" ) {
        $qsub .= "-q $queue "
}

$pid = open QSUB, " | $qsub";
die "Cannot run command '$qsub'\n" if ! kill(0, $pid); # Check that process exists
print QSUB "$cmd\n";		# Send cluster's task via qsub's STDIN
close QSUB;

exit(0);
```

for stat.pl
```
#!/usr/bin/perl

$exitCode = system "bqueues";

# OK
exit($exitCode);
```
for postMortemInfo.pl

```
#!/usr/bin/perl

die "Error: Missing arguments.\nUsage: postMortemInfo.pl jobId\n" if $#ARGV < 0 ;
$jobId = shift @ARGV;

#---
# Execute cluster command to show task details
#---
$exitCode = system "bjobs $jobId";

# OK
exit($exitCode);

```

**Comment by pcingola** [comment]
Great! I'll add them to the repository.
Thank you!

**Comment by ekernf01** [comment]
I ran into a couple errors while getting this working. Here they are, in case any of the info is useful to others. 

1. A Perl error about how the `ceil` subroutine is not defined. I got past it by adding `use POSIX;` to the top of `run.pl`.
2. An LSF error `Bad argument for option -n. Job not submitted.` I solved this by filling in a missing space: `    $qsub .= "-n $cpus";` becomes `$qsub .= "-n $cpus ";`.

**Comment by ekernf01** [comment]
Here's another one! I got an error about BDS being unable to find the `.exitCode` file. Solved by replacing the end of `run.pl` with this. The problem is that `bsub` does not conform to the criteria for a clusterGeneric run script: it prints too much junk aside from the job ID. 

```
use IPC::Open2;
$pid = open2(QSUB_IN, QSUB_OUT, " $qsub $cmd ", );
@result_split = split('<|>', <QSUB_IN>); # creates an @answer array
print @result_split[1] . "\n" ;
close QSUB_OUT;
close QSUB_IN;

# OK
exit(0);
```

**Comment by pcingola** [comment]
Added changes to scripts. I don't have an LSF cluster to test, so I didn't try them.

**Comment by ekernf01** [comment]
Well, these are working great for me so I think you can leave this issue closed until or unless it comes up again.
