### ISSUE TITLE
How to run in background

### ISSUE THREAD

**Issue by juanmas07** [pcingola/BigDataScript#58]
I'm using Debian and I cannot run bds in background.- Thank you

**Comment by kmhernan** [comment]
Another way is to use screen ... if that's what you mean by "background"

**Comment by juanmas07** [comment]
this is was I was looking for, I was misspelling the command:
nohup ./scriptName.bds &

@kmhernan I mean what you mean, how do you call it?

**Comment by kmhernan** [comment]
So I currently have a screen running BDS right now:

```
khernanez@lmem-cri:run$ screen -ls
There is a screen on:
	62945.pts-0.lmem-cri	(Detached)
1 Socket in /var/run/screen/S-khernanez.
```

I can attach the current screen like:

```
khernanez@lmem-cri:~$ screen -r 62945.pts-0.lmem-cri
```

Using another terminal session, I can detach the currently attached screen like:

```
khernanez@lmem-cri:~$ screen -d 62945.pts-0.lmem-cri
[62945.pts-0.lmem-cri detached.]
```

You can create a screen from scratch simply by typing: `screen`

You exit screens by typing `exit` in the currently attached screen (i'm sure control-d would work too)
