### ISSUE TITLE
Map of maps

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#59]
Is it possible to have maps of maps?  

I'm reading in a tab delimited list of samples (sampleName, fastq1, fastq2) and trying to store them in a map:

string{} samples;
string[] lines = cohort.readLines()
for ( string line : lines ) {
	string samplename
	string fastq1
	string fastq2
	(samplename, fastq1, fastq2) = line.split('\t')
	
	samples{samplename}{"fq1"} = fastq1
	samples{samplename}{"fq2"} = fastq2
}

However this causes a bunch of Exceptions.

**Comment by pcingola** [comment]
Unfortunately, not at the moment. 
I'll leave this issue open as a reminder to add more complex data types

**Comment by kmhernan** [comment]
Yes I yearn for being able to load JSON and/or YAML objects. But alas, I understand the complexities involved. I often make values a string with some delimeter or pattern to mimic having lists or nested maps even.
