### ISSUE TITLE
CheckTasksRunning.incMissingCount(98):	WARNING: Task PID '' not found. Incrementing count as 'missing': 1(max. allowed 3)

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#60]
BDS running with SGE doesn't seem to see some jobs finish.  This doesn't happen all the time.  Here's an example.  I have 27 samples consisting of 2 files each (fq1, fq2).  For each sample, I start a task to run fastqValidator on the fq file:

for (string s : samples) {
	string fastq1 = fq1{s}
	string fastq2 = fq2{s}

	task fastQValidator --file $fastq1
	task fastQValidator --file $fastq2
}

Sometimes the script will run without any issues.  Other times it will error out with:
CheckTasksRunning.incMissingCount(98):	WARNING: Task PID '19025' not found. Incrementing count as 'missing': 1(max. allowed 3)
CheckTasksRunning.incMissingCount(98):	WARNING: Task PID '19007' not found. Incrementing count as 'missing': 1(max. allowed 3)
CheckTasksRunning.incMissingCount(98):	WARNING: Task PID '19026' not found. Incrementing count as 'missing': 1(max. allowed 3)
CheckTasksRunning.incMissingCount(98):	WARNING: Task PID '19004' not found. Incrementing count as 'missing': 1(max. allowed 3)
CheckTasksRunning.incMissingCount(98):	WARNING: Task PID '19028' not found. Incrementing count as 'missing': 1(max. allowed 3)
CheckTasksRunning.incMissingCount(98):	WARNING: Task PID '19009' not found. Incrementing count as 'missing': 1(max. allowed 3)
CheckTasksRunning.incMissingCount(98):	WARNING: Task PID '19030' not found. Incrementing count as 'missing': 1(max. allowed 3)

**Comment by pcingola** [comment]
Are the "exitCode" files created and readable from the head node? Try running with "-log" and check if the files are there when the task finishes.
Example:

    $ bds -log -d z.bds
    ....

    $ ls -al z.bds.20150114_155340_078/task.line_4.id_1.exitCode 
    -rw-rw-r-- 1 pcingola pcingola 13 Jan 14 16:21 z.bds.20150114_155340_078/task.line_4.id_1.exitCode

This exitCode file is the way the slave node informs bds that the task has finished. So problem might be that the exitCode file cannot be read from the head node...

The incMissing message is produces because a "supposedly running" task disappeared from the queue (qstat does not show it). So if bds cannot detect the exitCode file, is assumes that the task is still running, then it checks using 'qstat' and finds out that the task is no longer there ("it disappeared from the cluster") so if it cannot be found for three times in a row, it marks the task as failed.

**Comment by golharam** [comment]
I had to run the pipeline a few times to get the error to happen, but I
have it.  I ran bds with '-v -d -l -s sge'.  I'm running build 0.999d.

Task failed:
        Program & line     : 'ExomePipeline.bds', line 56
        Task ID            :
'ExomePipeline.bds.20150115_110710_289/task.line_56.id_13'
        Task PID           : '22335'
        Task hint          : ' fastQValidator --file NTC_S5_L001_R1_001'
        Task resources     : 'cpus: 1   mem: -1.0 B     timeout: 86400
wall-timeout: 86400'
        State              : 'FINISHED'
        Dependency state   : 'ERROR'
        Retries available  : '1'
        Input files        : '[NTC_S5_L001_R1_001.fastq.gz]'
        Output files       : '[analysis/NTC.1.fastqValidator.txt]'
        Script file        :
'PD1_FFPE_CancerPanel/ExomePipeline.bds.20150115_110710_289/
task.line_56.id_13.sh'
        Exit status        : '0'
        Output file checks : 'Error: Output file 'NTC.1.fastqValidator.txt'
does not exist.'   Program            :

                # SYS command. line 57

                 fastQValidator --file NTC_S5_L001_R1_001.fastq.gz >
NTC.1.fastqValidator.txt


When I look in the bds temp directory, I see task.link_56.id_13.exitCode
with a value of 0 inside it.

The pipeline runs but this error occurs inconsistently so I suspect a
timing issue.  The directory is a local block storage directory on the head
node where bds is running.

**Comment by pcingola** [comment]
This sounds like a timing issue in the file system. Do you know 
what type of file system your cluster has? Apparently NFS introduces 
this kind of problems (one of the comments in issue #38 reports 
something similar happening every now and then).

I have a solution in mind, but involves a big refactoring and the main 
problem is that I still haven't found the way to reproduce the error.
It might take me a while to implement it.

In the mean time, I can try to add a "delay" as a workaround...

**Comment by biowang** [comment]
I got the silimar errror on qsub cluster
for( int i=0 ; i < 20 ; i++ ) {
        task echo Hi $i ; sleep 1 ; echo Done $i ; sleep 1
}

==================
CheckTasksRunning.incMissingCount(98):  WARNING: Task PID '3986.mu01' not found. Incrementing count      as 'missing': 4(max. allowed 3)
...
00:04:04.769    Error trying to find out post-mortem info on task (PID '3986.mu01').
        Exit code : 153
        Stdout    :
        Stderr    : qstat: Unknown Job Id 3986.mu01
...
Task failed:
        Program & line     : 'test_04.bds', line 4
        Task ID            : 'test_04.bds.20150203_150420_215/task.line_4.id_18'
        Task PID           : '3986.mu01'
        Task hint          : 'echo Hi 17 ; sleep 1 ; echo Done 17 ; sleep 1'
        Task resources     : 'cpus: 1   mem: -1.0 B     timeout: 86400  wall-timeout: 86400'
        State              : 'ERROR'
        Dependency state   : 'ERROR'
        Retries available  : '1'
        Input files        : '[]'
        Output files       : '[]'
        Script file        : '/llwang-works/installations/bds_test/test_04.bds.20150203_150420_215/t     ask.line_4.id_18.sh'
        Error message      : 'Task dissapeared from cluster's queue. Task or node failure?'
        Exit status        : '1'

**Comment by golharam** [comment]
Yes, even though I have a task that completes and the queue is empty, BDS
thinks it fails:

00:00:30.943    ExecutionerClusterSge 'ClusterSge[17]': Error trying to
find out post-mortem info on task (PID '27101').
    Command executed : ' qstat -f -j'
    Exit code        : 1
    Stdout           :
    Stderr           : Following jobs do not exist: 27101

Task failed:
    Program & line     : 'ExomePipeline.bds', line 262
    Task ID            :
'ExomePipeline.bds.20150203_101541_768/task.line_262.id_1'
    Task PID           : '27101'
    Task hint          : ' /ngs/ngs15/golharr/apps/jre1.7.0_67/bin/java
-jar /home/golharr/workspace/rgtools/dist/VCFToTab.jar
V=analysis/cohort.raw.hc.gatk.vcf O=analysis/coho'
    Task resources     : 'cpus: 1    mem: -1.0 B    timeout: 86400
wall-timeout: 86400'
    State              : 'FINISHED'
    Dependency state   : 'ERROR'
    Retries available  : '1'
    Input files        : '[analysis/cohort.raw.hc.gatk.vcf]'
    Output files       : '[analysis/cohort.raw.hc.gatk.txt]'
    Script file        :
'/net/kraken/ng15/golharr/work/PD1_FFPE_CancerPanel/ExomePipeline.bds.20150203_101541_768/
task.line_262.id_1.sh'
    Exit status        : '0'
    Output file checks : 'Error: Output file
'analysis/cohort.raw.hc.gatk.txt' does not exist.'    StdErr (10 lines)  :
        [Tue Feb 03 10:15:58 EST 2015] tools.VCFToTab
VCF=analysis/cohort.raw.hc.gatk.vcf
OUTPUT=analysis/cohort.raw.hc.gatk.txt    VERBOSITY=INFO QUIET=false
VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000
CREATE_INDEX=false CREATE_MD5_FILE=false
        [Tue Feb 03 10:15:58 EST 2015] Executing as
golharr@kraken.pri.bms.com on Linux 2.6.32-431.23.3.el6.x86_64 amd64; Java
HotSpot(TM) 64-Bit Server VM 1.7.0_67-b01; Picard version: null JdkDeflater
        INFO    2015-02-03 10:15:58    VCFToTab    Version 0.02b
        INFO    2015-02-03 10:16:00    VCFToTab    Finished! Total of 548
lines processed.
        [Tue Feb 03 10:16:00 EST 2015] tools.VCFToTab done. Elapsed time:
0.04 minutes.
        Runtime.totalMemory()=2058354688

**Comment by pcingola** [comment]
@biowang 
It looks like your cluster removed the task from the queue before the NFS propagated 
the state of the corresponding "exitCode". This should not be a problem, since the counter has 
to increase the counter to 'TASK_NOT_FOUND_DISAPPEARED' times (by default set to 3) 
before considering the task as failed. Since this is done once per minute, the NFS update has 
to be really slow (over 3 minutes) to produce a problem.

The second message ("Error trying to find out post-mortem info on task (PID '3986.mu01')." looks like
is produced because your 'qstat' command doesn't recognize the jobID. Is it possible that the 
cluster does not give information on finished jobs?

**Comment by pcingola** [comment]
@golharam Does your cluster give information when you 
run "qstat -f -j $jobID" after the job finished?

**Comment by golharam** [comment]
No.  qstat reports:

Following jobs do not exist:
...

**Comment by pcingola** [comment]
OK, so postmortem stats will always fail. 
I should add a config option for this case.

**Comment by pcingola** [comment]
Added 'clusterPostMortemDisabled' parameter to the config file. It disables post mortem info requests so the don't produce errors

**Comment by tboyarski** [comment]
Hey Pablo,

I'm currently trying to submit a job, using the latest Git-Repo pull, 0.99999g, and this issue is still appearing. I've set clusterPostMortemDisabled=true, but this had no effect. Any thoughts? How best can I re-approach this topic? I can post log-files etc, just let me know if I should do it here or open up another issue.

Cheers, Tim

**Comment by rfarouni** [comment]
I have the same problem here

**Comment by pcingola** [comment]
Hi,
  Can you send more details about this? What exactly is the context /
cluster type, etc.
Can you send a simple task and send the debug output (i.e. run bds with
'-debug' command line option)
Thank you

   Pablo
