### ISSUE TITLE
Named SGE jobs

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#61]
Right now when jobs are scheduled in SGE, they all have the name STDIN.  Can they be named based on their task id or something similar?

**Comment by kmhernan** [comment]
I wonder if setting the additional queue args to `-N $taskID` would work?? But I agree having a `jobName` parameter in tasks would be a use addition.

**Comment by golharam** [comment]
Has this been added in 0.999h?  I saw something in the code about naming jobs

**Comment by kmhernan** [comment]
Both the YAML output and the taskName works now, I'm not sure which tagged version though. I have been pulling from HEAD!

**Comment by golharam** [comment]
How do you specify the name?  I didn't see anything in the docs?

task ( outfile <- infile, taskName="taskX") {...}

?

**Comment by kmhernan** [comment]
I don't think it has become part of the "official" build yet, but perhaps @pcingola can chime in. Anyways, here is a snippet: `task( paired, [out1, out2] <- [fq1, fq2], cpus := threads, mem := jobMem, taskName := "fastqc.$rg" )`

**Comment by pcingola** [comment]
Yes, I have to update the docs, but what Kyle mentions is the way to use it: 

    task( ... , taskName := "my task name")  { ....

**Comment by pcingola** [comment]
Docs updated, closing this.

**Comment by golharam** [comment]
Actually, this is still an issue.  I've named all my tasks but qstat shows
STDIN instead of the job name:

job-ID  prior   name       user         state submit/start at
queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
  52282 0.00893 STDIN      golharr      r     05/01/2015 06:01:18
all.q@kraken.pri.bms.com          64
  52517 0.00893 STDIN      golharr      r     05/01/2015 10:18:45
all.q@shamayim.pri.bms.com         1
  52518 0.00893 STDIN      golharr      r     05/01/2015 10:18:45
all.q@shamayim.pri.bms.com         1

**Comment by kmhernan** [comment]
It never changed the job name, it only changes the internal task name which you can see in the logs, HTML, and yaml outputs.

**Comment by golharam** [comment]
Would it be difficult to change the job name?  It would mean passing -N
<jobname> to qsub

**Comment by pcingola** [comment]
I'll give it a try, but one of the problems is that this naming functionality is not on every cluster system...
