### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#62]
I understand task dependencies are listed as:

task abc ( outfile <- infile) {...}
or
task abc ( outfile <- [infile1, infile2, infile3] ) {...}

but what about when I have a Map of files, where each file corresponds to a sample.  How do I specify this list as a dependency? I tried using the Map variable name with and without brakets, but it doesn't work, so I'm not sure what to do.

**Comment by pcingola** [comment]
You can use 'keys()' or 'values()' to get a list form a map

    map := { 'hi' => 'hola', 'bye' => 'adios' }
    k := map.keys()
    v := map.values()
    print "map: $map\n"
    print "keys: $k\n"
    print "values: $v\n"


    $ z.bds
    map: { bye => adios, hi => hola }
    keys: [bye, hi]
    values: [adios, hola]


So something like this should work:

    task( out <- map.keys() ) { ... }

or 

    task( out <- map.values() ) { ... }


I hope this helps.

**Comment by golharam** [comment]
That seems to work, but not for the output values.  Here's what I have:

task ( realignedBamFiles.values() <- "analysis/indelrealigner.list" ) { ... }

where realignedBamFiles is a string{} data type.  The error I get is:

Compiler messages:
ERROR [ file 'ExomePipeline.bds', line 209 ] :  Expression should be string or string[]

**Comment by pcingola** [comment]
It seems to work OK for me:

    in := 'in.txt'
    out := 'out.txt'
    map := { in => out }
 
    print "map : $map\n"
 
    # New input file
    sys date > $in
 
    task( map.values() <- map.keys() ) {
        sys echo RUNNING TASK ; cp $in $out
    }

When I run it, I get

    $ ./z.bds
    map : { in.txt => out.txt }
    RUNNING TASK

Are you using the latest version? Can you send me a minimal 
script that shows the error condition you are talking about?

**Comment by golharam** [comment]
I got it working.  My script was getting messy and I cleaned it up.  Now all is good.  I'm going to close this as a non-issue.

**Comment by golharam** [comment]
OK, I've changed everything to .values() and all is good.
