### ISSUE TITLE
-dryRun still causes CHP file to get created

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#64]
In testing my pipeline, I'm using -dryRun to see what will happen.  I have a wait command in my script that waits on some previous jobs to finish.  With -dryRun, I'm still getting .chp files created.  I would expect to not get any files written.

**Comment by pcingola** [comment]
Seems to work OK in this simple test:

    # Only z.bds in this dir
    $ ls
    z.bds

    # Script is a simple task
    $ cat z.bds
    task echo Hi

   # Run script
    $ bds -dryRun z.bds
    00:00:00.021    Dry run task:
        Program & line     : 'z.bds', line 3
        Task ID            : 'z.bds.20150127_103430_211/task.line_3.id_1'
        Task PID           : 'null'
        Task hint          : 'echo Hi'
        Task resources     : 'cpus: 1   mem: -1.0 B timeout: 86400  wall-timeout: 86400'
        State              : 'NONE'
        Dependency state   : 'OK'
        Retries available  : '0'
        Input files        : '[]'
        Output files       : '[]'
        Script file        : '/Users/pcingola/test/z.bds.20150127_103430_211/task.line_3.id_1.sh'
        Exit status        : '0'
        Program            :
            echo Hi
   
    # No 'chp' file created..
    $ ls
    z.bds


Can you send a minimal script that shows the issue?

**Comment by pcingola** [comment]
This one seems to be solved. Closing.
