### ISSUE TITLE
output from tasks are printed out on the console

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#65]
My pipeline uses task extensively for just about everything.  Each task is fed to SGE.  All the output from the tasks are printed to my main console.  Is there a way to get the output of each task saved to a file instead of printed out on the console?  The output of all the tasks get intermixed and becomes pretty pointless.

**Comment by pcingola** [comment]
BDS does this by default, but deletes all those files when the script finishes.
You can use "-log" (or "-l") command line option to avoid cleaning up log files.

**Comment by golharam** [comment]
What about output from ExecutionerClusterSge?  This output also gets mixed with the task output on my console. I'm not specifying any parameters except -s to bds

**Comment by pcingola** [comment]
By default, task's output is shown to the consoles and saved to separate 
log files (per task). If "-log" is specified, then log files are not cleaned up on exit.
You can follow a specific task by using "tail" on the log files (is that what you 
want to do?)

The console also outputs bds messages (like ExecutionerClusterSge).

I'm not sure what you are trying to do...

**Comment by golharam** [comment]
I want to find a way such that I don't get any output except for the print
statements in my script.

**Comment by pcingola** [comment]
Ohhh! OK, now I get it. 
So, I should provably add a "quiet" mode in which nothing else gets printed.

**Comment by kmhernan** [comment]
So, I have dealt with this by redirecting the stderr/stdout explicitly:

```
task {
  sys sometool 2> somtool.logs
}
```

This of course is built into the entire pipeline and named in a sane way, and organized to one particular parent directory for the run. Then, I used `println()` statements as a logger throughout the pipeline. So, when I run my bds script, this will appropriately separate stuff:

```
bds myPipelinne.bds > printlnStatements.logs 2> bds-stuff.logs
```

**Comment by pcingola** [comment]
Using the "-log" you get all STDOUT and STDERR already 
separated (although the file names are taskIDs, which can be cryptic).

I'm adding a "-quiet" command line option that doesn't show anything 
from "task/sys" commands (only print statements are shown on your 
console).

**Comment by pcingola** [comment]
OK, committed "-quiet" command line option (does not show sys / task outputs)


  # Normal (no -quiet)
  $ bds z.bds
  OUTPUT: print
  OUTPUT: sys
  OUTPUT: task

  # Using '-quiet'  doesn't show sys or task
  $ bds -quiet z.bds
  OUTPUT: print

  # Using '-quiet' plus '-log' you also get STDOUT/STDERR in per task log files
  $ bds -log -quiet z.bds 
  OUTPUT: print

  $ ls -al
  total 32
  drwxr-xr-x   5 pcingola  staff   170 27 Jan 23:49 .
  drwxr-xr-x+ 90 pcingola  staff  3060 27 Jan 23:48 ..
  -rwxr-xr-x   1 pcingola  staff    95 27 Jan 23:46 z.bds
  drwxr-xr-x   6 pcingola  staff   204 27 Jan 23:49 z.bds.20150127_234907_321
  -rw-r--r--   1 pcingola  staff  8482 27 Jan 23:49 z.bds.20150127_234907_321.report.html

  $ cat z.bds.20150127_234907_321/task.line_5.id_2.stdout 
  OUTPUT: task

Give it a try and let me know how it works for you.

**Comment by golharam** [comment]
Will do.  As a another note, I currently have 
task {
sys ... 2>&1 > out.txt
}

But stderr isn't getting redirected.  Is BDS stripping that off?

**Comment by golharam** [comment]
Nevermind....I need to set my taskShell to bash instead of sh.

**Comment by golharam** [comment]
I'm specifying my taskShell to be /bin/bash so I know the syntax is correct.

**Comment by kmhernan** [comment]
@golharam perhaps it needs to be

```
task {
  sys ... > out.txt 2>&1
}
```

That's what I have been currently using and it works... in both `/bin/bash` and `/bin/sh`

**Comment by golharam** [comment]
Odd, because that's not working for me.  Hmmm.

**Comment by kmhernan** [comment]
@golharam *scratches head* 

A for realsies example I have:

```
      tid := task( rawVcf <- [nbam, tbam], cpus := 1, mem := runMem ) {
        sys $mod
        sys $java $mutectExe -T MuTect -R $reference$extended$cosmic$onlyPass$tumorLod$normalLod \
            -dbsnp $dbsnp --min_qscore $minMapQ --input_file:normal $nbam \
            --input_file:tumor $tbam $rods --tumor_sample_name $tumorID \
            --normal_sample_name $normalID -S LENIENT --out $statFile \
            --coverage_file $covFile -vcf $rawVcf -L $interval > $olog 2>&1
      }
```

That is bananas that it isn't working for you. I am using this build `BigDataScript 0.999d (build 2015-01-28), by Pablo Cingolani`. Is a particular tool you are using that is doing this? Just out of curiosity! I had a lot of trouble with `bwa` because of all the piping you need to redirect `stderr` each step:

```
task( [ sortBam1, sortBam2 ] <- fqLst, cpus := bwaAlnThreads, mem := bwaAlnMem ) {
          sys set -o pipefail
          sys $mods
          sys echo "*****Running paired-end*****" > $alnLog
          sys $bwaAlnExe aln$offsetOpt$barcodeOpt$readTrimOpt -t $bwaAlnThreads \
              $reference $fq1 > $sai1 2>> $alnLog
          sys $bwaAlnExe aln$offsetOpt$barcodeOpt$readTrimOpt -t $bwaAlnThreads \
              $reference $fq2 > $sai2 2>> $alnLog
          sys sleep 1
          sys $bwaAlnExe sampe$maxOccurOpt -r $rgString $reference $sai1 $sai2 $fq1 $fq2 2>> $alnLog \
              | $samtoolsExe view -q $minMapQ -F 4 -SbT $reference - > $rawBam1 2>> $alnLog
          sys $samtoolsExe sort -@ $bwaAlnThreads $rawBam1 $sortPfx1 2>> $alnLog
          sys $samtoolsExe index $sortBam1 2>> $alnLog
}
```

That kept anything from spilling into my BDS logs, pre Pablo's addition of `-quiet`. Also, I had to use `/bin/bash` for tasks and add the `set -o pipefail` because it didn't seem to catch errors correctly (albeit, at the time I didn't realize that I had a race-condition from my `par` statements).

**Comment by golharam** [comment]
I too am using the latest version of BDS pulled down from github.  My task
is:

string[] outputFiles = ["analysis/" + fastq1.baseName(".fastq.gz") +
"_fastqc.html", "analysis/" + fastq1.baseName(".fastq.qz") + "_fastqc.zip",
"analysis/" + fastq2.baseName(".fastq.gz") + "_fastqc.html", "analysis/" +
fastq2.baseName(".fastq.qz") + "_fastqc.zip"]
task (outputFiles <- [fastq1, fastq2], cpus := 2) {
  sys $fastqcApp -t 2 --outdir=analysis/ $fastq1 $fastq2 2>&1 >
analysis/$replicate.fastqc.txt
}

I run my script and the console output shows output from stderr

**Comment by pcingola** [comment]
I think it should be

    command > out.txt 2>&1 

instead of 

     command 2>&1 > out.txt

**Comment by pcingola** [comment]
Closing: Looks like this has been solved by the "-quiet" command line option.
