### ISSUE TITLE
Multiple goals

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#71]
Could you make bds have multiple goal variables like the following?

    dep( SAIFILE1 <- FASTQFILE1 ) {
        sys bwa aln $BWAPARAM -t $NTHREADSBWA $BWAINDEXNAME $FASTQFILE1 > $SAIFILE1
    }
    dep( SAIFILE2 <- FASTQFILE2 ) {
        sys bwa aln $BWAPARAM -t $NTHREADSBWA $BWAINDEXNAME $FASTQFILE2 > $SAIFILE2
    }

    dep( [RAWBAMFILE, RAWBAMFILEMAPSTATS] <- [SAIFILE1, SAIFILE2] ) {
         // ~~~~~~~~~~~
    }
    goal( [RAWBAMFILE, RAWBAMFILEMAPSTATS] )    // <--- didn't work

**Comment by pcingola** [comment]
Hi,
  I added a new functionality to address this issue. Now you can 
use 'taskId' as a goal. So, in an example like the one you show 
it would be:

    #!/usr/bin/env bds

    in1 := "in1.txt"
    in2 := "in2.txt"

    out1 := "out1.txt"
    out2 := "out2.txt"

    out1_2 := "out1_2.txt"
    out2_1 := "out2_1.txt"

    # Create new files and remove old ones
    sys rm -f $in1 $in2 $out1 $out2 $out1_2 $out2_1
    sys date > $in1 ; sleep 1 ; date > $in2

    dep( out1 <- in1 ) { 
        sys cp $in1 $out1 ; echo $out1
    }   

    dep( out2 <- in2 ) { 
        sys cp $in2 $out2 ; echo $out2
    }   

    tid := dep( [out1_2, out2_1] <- [out1, out2] ) { 
        sys cat $out1 $out2 > $out1_2 ; echo $out1_2
        sys cat $out2 $out1 > $out2_1 ; echo $out2_1
    }   

    goal( tid )

And when you run it, you get the expected output:

    $ ./z.bds
    out1.txt
    out2.txt
    out1_2.txt
    out2_1.txt

Let me know if it works OK for you.
