### ISSUE TITLE
Variable names in a curved bracket

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#72]
Could you make bds variables can be referred as ${varname} just like in bash shell script? I need to use underscore in var. names for better code readability. Without brackets $BWA_PARAM is interpreted like "$BWA" + "_PARAM".

// this works
        sys bwa aln $BWAPARAM -t $NTHREADSBWA $BWAINDEXNAME $FASTQFILE1 > $SAIFILE1

// this didn't
        sys bwa aln ${BWA_PARAM} -t ${NTHREADS_BWA} ${BWA_INDEX_NAME} ${FASTQ_FILE1} > ${SAI_FILE1}

**Comment by pcingola** [comment]
Fixed, thank you for reporting the issue.

    $ cat z.bds
    #!/usr/bin/env bds
    BWA_PARAMS := "parameters here"
    task echo bwa $BWA_PARAMS

    $ ./z.bds
    bwa parameters here

looks like it's working OK now.
