### ISSUE TITLE
boolean operators precedence

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#75]
There are two issues; 1) operator== precedence and 2) operator== not working for boolean var.
Please take a look at the following code:

#!/usr/bin/env bds
#

int a = 1
int b = 2

bool aa = true
bool bb = false

print( (a==1) || (b==2) + "\n")

print( a==1 || b==2 + "\n") // Fatal error: test.bds, line 11, pos 13. java.lang.Long cannot be cast to java.lang.Boolean
print( (aa==true) || (bb==false) + "\n") // Fatal error: test.bds, line 12, pos 11. Unknown return type bool for expression ExpressionE

**Comment by pcingola** [comment]
Hi, thank you for the report.
I'll try to fix it as soon as possible.

**Comment by pcingola** [comment]
OK, I think I fixed it.
Now the output of your example program would be "truetruetrue" (without 
any "\n"). I know this looks counter intuitive, but it seems to be the right 
answer. Take a look at the detailed explanations below...(let me know 
what you think).

    #!/usr/bin/env bds

    int a = 1
    int b = 2
 
    bool aa = true
    bool bb = false
 
    // This one should print "true" (without trailing "\n")
    // Details:
    //     ( (a==1) || (b==2) + "\n")
    //     ( (1==1) || (2==2) + "\n")
    //     (  true  || true + "\n"  )
    //     (  true  || "true\n"     )
    //     (  true  || true         ) <- Non-empty string converts to true boolean
    //     true
    print( (a==1) || (b==2) + "\n")
 
    // This one should print "true" (without trailing "\n")
    // Details:
    //     ( a==1 || b==2 + "\n")
    //     ( a==1 || b=="2\n"   )
    //     ( 1==1 || 2=="2\n"   )
    //     ( true || "2"=="2\n" )
    //     ( true || false      )
    //     true
    print( a==1 || b==2 + "\n")
 
    // This should print "true" (without trailing "\n")
    // Details:
    //     ( (aa==true)   || (bb==false)    + "\n")
    //     ( (true==true) || (false==false) + "\n")
    //     (  true        ||  true          + "\n")
    //     (  true        ||  "true\n"            )
    //     true
    print( (aa==true) || (bb==false) + "\n")

When you execute it, you get:

    $ ./test/z.bds 
    truetruetrue$

**Comment by pcingola** [comment]
Looks like this is OK now, I'm closing it.
