### ISSUE TITLE
mem in bds.config

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#77]
Hello!

I am running BDS job on sge cluster. I found that "mem" is only taken as LONG type in the task parameter or in bds.config. People typically use G or M instead of byte for memory limit... Could you make mem parameter take string (e.g. "4G" or "512M") instead of integer?
```
//////////////////////// bds script
#!/usr/bin/env bds

for (int i=1;i<=2;i++ ) {
    par fnc1( i )
}

void fnc1( int i ) {
    task ( taskName := "test", cpus := 2, timeout := 3600, mem := 20000000000 ) {
        sys echo task $i waiting for 60 secs
        sys sleep 60
    }
}
```
```
//////////////////////// bds.config 
# mem in bytes
mem = 10000000000
# timeout in seconds
timeout = 44444

sge.pe = shm
sge.mem = h_vmem
sge.timeout = h_rt

clusterRunAdditionalArgs = -V
```

**Comment by leepc12** [comment]
Is it also possible to have pass custom task argument to qsub? Some of my job needs to be run with "qsub -q extended".

```
task ( taskName := "test", cpus := 2, timeout := 3600, mem := 20000000000, custom := "-q extended" ) {
}
```

**Comment by leepc12** [comment]
I found that mem and timeout in bds.config are not passed to the sge job.

```
#!/usr/bin/env bds

for (int i=1;i<=2;i++ ) {
    par fnc1( i )
}

void fnc1( int i ) {
    //task ( taskName := "test", cpus := 2, timeout := 3600, mem := 5000000000) {
    task ( taskName := "test", cpus := 2 ) {
        sys echo task $i waiting for 60 secs
        sys sleep 60
    }
}
```
sge.pe = shm
sge.mem = h_vmem
sge.timeout = h_rt

clusterRunAdditionalArgs = -V

mem = 10000000000
timeout = 43200
```
```
 116088 0.00000 STDIN      leepc12      qw    03/11/2015 16:24:11                                    2        
       Full jobname:     STDIN
       Requested PE:     shm 2
       Hard Resources:   
       Soft Resources:   
       Binding:          set linear:slots
 116089 0.00000 STDIN      leepc12      qw    03/11/2015 16:24:11                                    2        
       Full jobname:     STDIN
       Requested PE:     shm 2
       Hard Resources:   
       Soft Resources:   
       Binding:          set linear:slots
```

**Comment by leepc12** [comment]
I also found that mem, timeout alone in task() are not passed to qsub.
```
#!/usr/bin/env bds

for (int i=1;i<=2;i++ ) {
    par fnc1( i )
}

void fnc1( int i ) {
    //task ( taskName := "test", true, cpus := 2, timeout := 3600, mem := 5000000000) {
    //task ( taskName := "test", cpus := 2 ) {
    //task ( taskName := "test", true, timeout := 3600, mem := 5000000000) {
    task ( taskName := "test", true, timeout := 3600 ) {
        sys echo task $i waiting for 60 secs
        sys sleep 60
    }
}
```
qstat -r says walltime is 21000, not 3600. The same thing happens for mem too. If one of them alone is specified in task() they are not passed to qsub.
```
 128796 0.45127 STDIN      leepc12      r     03/12/2015 11:17:31 standard@scg3-1-2.local            1        
       Full jobname:     STDIN
       Master Queue:     standard@scg3-1-2.local
       Requested PE:     shm 1
       Granted PE:       shm 1
       Hard Resources:   h_vmem=9G (0.000000)
                         h_rt=21000 (0.000000)
       Soft Resources:   
       Binding:          set linear:slots
 128797 0.45125 STDIN      leepc12      r     03/12/2015 11:17:31 standard@scg3-1-2.local            1        
       Full jobname:     STDIN
       Master Queue:     standard@scg3-1-2.local
       Requested PE:     shm 1
       Granted PE:       shm 1
       Hard Resources:   h_vmem=9G (0.000000)
                         h_rt=21000 (0.000000)
       Soft Resources:   
       Binding:          set linear:slots
```

**Comment by pcingola** [comment]
OK, I'll take a look at it asap.
Thank you for the bug report!

**Comment by kmhernan** [comment]
I find using the builtin `G`, `M`, etc. are just as simple:

```
int memUsage = 5 * G
```

**Comment by pcingola** [comment]
OK, there are several issues here:
  1) Trying to specify 'mem' in the config file by using 'G', 'M' suffixes does not work.
  2) 'mem' form config file is not correctly passed to SGE
  3) Same for 'timeOut' 
 
I'll address each one separately...

**Comment by pcingola** [comment]
First issue solved: Now 'mem' parameter in config file can use letters to specify a value (e.g. '5 G')

**Comment by pcingola** [comment]
I've tried issues 2 and 3 and they work OK on my 
environment. Here is the example:


Config file:

    mem = 1G
    timeout = 3600
    sge.pe = shm
    sge.mem = h_vmem
    sge.timeout = h_rt


Program:

    #!/usr/bin/env bds
    task echo hi

Running:

    bds -d -s sge z.bds

     ... // debug lines edited for readability
    00:00:00.514	CmdLocal: Executing  qsub -pe shm 1 -l h_vmem=1073741824 -l h_rt=01:02:00 -o /Users/pcingola/Documents/workspace/BigDataScript/z.bds.20150403_113416_606/task.z.line_6.id_1.stdout.cluster -e /Users/pcingola/Documents/workspace/BigDataScript/z.bds.20150403_113416_606/task.z.line_6.id_1.stderr.cluster

As you can see, the parameters are correctly passed to the cluster: "qsub -pe shm 1 -l h_vmem=1073741824 -l h_rt=01:02:00" (bds adds 2 minutes to the timeout just to allow the controlling process to find out before it is killed by the cluster).

If I change the program to:

    task( mem:= 2*G, timeout := 2*hour ) sys echo hi

Then I get: "qsub -pe shm 1 -l h_vmem=2147483648 -l h_rt=02:02:00 ..." 
So, I'm a little bit puzzled because everything seems to be working OK. 

Can you confirm if you still see this problem using the latest 'HEAD' version (0.999 J) ?

**Comment by pcingola** [comment]
Performed some more tests and everything seems to work OK.
I'm closing for the moment, please re-open if this is still an issue.
