### ISSUE TITLE
definition of local variable in task () not working

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#79]
In the BDS manual (http://pcingola.github.io/BigDataScript/bigDataScript_manual.html), there is an example for local variable definition in task () like the following:

A task with mutiple inputs and outputs dependencies, using 4 CPUs and declaring a local variable 'tmp'
```
task ( [out1, out2] <- [in, in2] , cpus := 4 , tmp := "$in.tmp" ) {
	sys cat $in1 | grep "^results" > $out1
	sys cat $in1 $in2 > $tmp
	sys wc -l $tmp | wc -l > $out2
}
```

However, it doesn't work

```
#!/usr/bin/env bds

task ( tmp := "TEST" ) {
    sys echo $tmp
}
```

```
$ bds test_sge.bds

Compiler messages:
ERROR [ file 'test_sge.bds', line 4 ] :	Symbol 'tmp' cannot be resolved
```

**Comment by pcingola** [comment]
Fixed. 
Apparently I screwed up variable declaration processing order when I refactored the code (but only for variables declared within task options).
Thank you for your bug report!
