### ISSUE TITLE
Goal and dependencies

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#81]
Hi Pablo - I understand the concept behind goals and dependencies and only run the jobs needs to get to the goal, but I was wondering how this works with tasks?

Also, I wonder if it would be enough to have a dependency tree and only run the tasks where the output files are out of date.  I ask because I am trying to conserve disk space by deleting intermediate files along the way, but the tasks get rerun.  I haven't figured out how to specify goals/dependencies with tasks, but wondered if that's even needed since BDS can build a dependency tree of the tasks anyway.  I would think goals/dependencies would be automatic...

Ryan

**Comment by pcingola** [comment]
I'm not sure what you mean...
Goals are automatic and if the ultimate goal is up to date respect to the input files, nothing is done. This means that you don't need to keep intermediate files.
E.g.

   dep( [inter_1, inter_2] <- [in1, in2] ) ...
   dep( out <- [inter_1, inter_2] ) ...
   goal out

If 'out' is up to date respect to 'in1' and 'in2', then nothing happens (even if 'inter_1' and 'inter_2' have been deleted).
Of course, this is how "it is supposed to work", but if you think there is a bug, send me an example and I'll try to take a look at it.

**Comment by golharam** [comment]
How do I do this?

task ( inter1 <- input1 ) { ...}
task ( inter2 <- intput2 ) {...}
task ( inter3 <- [inter1, inter2]) {...}
task ( output <- inter3 ) {...}

Along the way I want to delete inter1, inter2, and inter3.  If I rerun my
script, I don't want inter1, inter2, and inter3 to be rerun, since output
is already present.  I add the following before the task statements:

dep ( inter1 <- input1 )
dep ( inter2 <- input2 )
dep ( inter3 <- [inter1,inter2] )
dep ( output, inter3 )
goal out

I get the following error when I do 'bds -dryRun ExomePipeline.bds'

Exception in thread "main" java.lang.RuntimeException: Error creating
object: Class 'ca.mcgill.mcb.pcingola.bigDataScript.lang.ProgramUnit'
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:129)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:74)
        at
ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.compile(BigDataScript.java:318)
        at
ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.runCompile(BigDataScript.java:974)
        at
ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.run(BigDataScript.java:926)
        at
ca.mcgill.mcb.pcingola.bigDataScript.BigDataScript.main(BigDataScript.java:191)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native
Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown
Source)
        at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:123)
        ... 5 more
Caused by: java.lang.RuntimeException: Error parsing file
'ExomePipeline.bds', line 1, char 18, node ''
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.doParse(BigDataScriptNode.java:112)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.ProgramUnit.<init>(ProgramUnit.java:39)
        ... 10 more
Caused by: java.lang.RuntimeException: Error creating object: Class
'ca.mcgill.mcb.pcingola.bigDataScript.lang.ForLoopList'
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:129)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:74)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.factory(BigDataScriptNode.java:127)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.Block.parse(Block.java:35)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.ProgramUnit.parse(ProgramUnit.java:53)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.doParse(BigDataScriptNode.java:110)
        ... 11 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native
Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown
Source)
        at
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNodeFactory.factory(BigDataScriptNodeFactory.java:123)
        ... 16 more
Caused by: java.lang.NullPointerException
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.ForLoopList.toString(ForLoopList.java:177)
        at java.lang.String.valueOf(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.doParse(BigDataScriptNode.java:112)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.BigDataScriptNode.<init>(BigDataScriptNode.java:50)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.Statement.<init>(Statement.java:13)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.StatementWithScope.<init>(StatementWithScope.java:18)
        at
ca.mcgill.mcb.pcingola.bigDataScript.lang.ForLoopList.<init>(ForLoopList.java:37)
        ... 21 more

**Comment by pcingola** [comment]
You get the error on the first or the second snippet?
Can you send me 'ExomePipeline.bds' so I can debug it?

Here is a complete example of what you want:

    #!/usr/bin/env bds
 
    input1 := "input1.txt"
    input2 := "input2.txt"
    inter1 := "inter1.txt"
    inter2 := "inter2.txt"
    inter3 := "inter3.txt"
    output := "output.txt"
 
    dep ( inter1 <- input1 ) {
        sys cat $input1 > $inter1; echo inter1
    }
 
    dep ( inter2 <- input2 ) {
        sys cat $input2 > $inter2; echo inter2
    }
 
    dep ( inter3 <- [inter1,inter2] ) {
        sys cat $inter1 $inter2 > $inter3; echo inter3
    }               
                    
    dep ( output <- inter3 ) {
        sys cat $inter3 > $output; echo output
    }                 
                      
    goal output

Now we create input files:

    $ echo IN_1 > input1.txt
    $ echo IN_2 > input2.txt

We run it for the first time (note that all tasks are run):

    $ ./z.bds 
    inter1
    inter2
    inter3
    output

Now we run it again (nothing happens since 'output' is up to date):

    $ ./z.bds 
    $

We delete intermediate files and run it again (nothing happens since the output is still up to date taking into account the dependency graph):

    $ rm inter*
    $ ./z.bds 
    $ 

So, as you can see, 'dep' operator is robust to deleting intermediate files.

**Comment by golharam** [comment]
Can you send me your email?  I don't want to post my script up here (yet).
The way you specified works too but doesn't utilize a grid engine.  I
thought using a task was the correct way to utilize a grid engine.  Can I
do this:

dep (..) { task { sys ... } }

**Comment by pcingola** [comment]
I'm not sure what you mean by "it doesn't utilize Grid engine"
If you specify system='sge' it will submit the jobs to your cluster...
email: pablo dot e dot cingolani at gmail

**Comment by pcingola** [comment]
Looks like this one has been solved... closing it.
Please re-open if you think it this is still a problem.
