### ISSUE TITLE
Error when trying to execute a checkpoint

### ISSUE THREAD

**Issue by juanmas07** [pcingola/BigDataScript#85]
line 1:0 token recognition error at: ''
Compiler messages:
ERROR [ file '' ] :	Could not compile /home/trigo/bds/18-3-15/pipeline.bds.line_134.chp :LexerNoViableAltException('')

**Comment by pcingola** [comment]
Sorry, but if you do not provide a minimal example of the script producing the error, there is no way to asses whether this is a bug or just a user's errror.

**Comment by juanmas07** [comment]
What information should I submit?

**Comment by juanmas07** [comment]
this is my pipeline

#!/usr/bin/env bds

string tae = "data/tae/miRNAlib.fa";
string scaff = "data/4D/4d.fasta";
string scaff_name = "4D";
string scaff_db = "data/4D/4Ds";
string trep = "data/TREP/TREP_total.fa";
string trep_db = "data/TREP/TREP_db";
string iWGSC2 = "data/IWGSC2/IWGSC2.fasta";
string iWGSC2_db = "data/IWGSC2/IWGSC2_db";
string cmd, tae_ , out, date;
string iWGSC2_cDNA = "data/IWGSC2/Triticum_aestivum.IWGSC2.25.cdna.all.fa";
	
cmd = "makeblastdb -dbtype 'nucl' -in " + scaff + " -out " + scaff_db
stage("makeblastdb_sumirfind", cmd);

cmd = "makeblastdb -dbtype 'nucl' -in " + trep + " -out " + trep_db
stage("makeblastdb_trep", cmd);

cmd = "makeblastdb -dbtype 'nucl' -in " + iWGSC2 + " -out " + iWGSC2_db
stage("makeblastdb_IWGSC2", cmd);


string hairpins = "";
string scaff_db_ids = "data/4D/4Ds_ids_";

cmd = "python scripts/filter_srnalib.py -i " + tae + " -o " + tae + ".filtered" + " -n 21";
stage("filterSRNALibs", cmd);

cmd = "blastn -task blastn-short -query " + tae + ".filtered" + " -db " + scaff_db + " -ungapped -penalty -1 -reward 1 -outfmt 6 -out " + tae + ".filtered.allhits";
stage("blast_srna", cmd);

cmd = "python scripts/filter_blastn.py -n 21 -i " + tae + ".filtered.allhits -o " + tae + ".filtered.allhits.perfectmatch";
stage("perfectmatch", cmd);

cmd = "python scripts/splitter.py --allhits " + tae + ".filtered.allhits.perfectmatch --fasta " + scaff + " -o " + scaff + ".splitted -n 250";
stage("split_scaffold", cmd);

cmd = "makeblastdb -dbtype 'nucl' -in " + scaff + ".splitted -out " + scaff_db_ids + " -parse_seqids";
stage("makeblastdb_sumirfold_splitted", cmd);

cmd = "blastn -task blastn-short -query " + tae + ".filtered -db " + scaff_db_ids + " -ungapped -penalty -1 -reward 1 -outfmt 6 -out " + tae + ".filtered.allhits.perfectmatch.splitted";
stage("blast_srna_splitted", cmd);

cmd = "python scripts/filter_blastn.py -n 21 -i " + tae + ".filtered.allhits.perfectmatch.splitted -o " + tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2";
stage("perfectmatch2", cmd);

cmd = "python scripts/selection.py -i " + tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2 -o " + tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection";
stage("selection", cmd);

cmd = "python scripts/blast_splitted_filter.py -i " + tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection -o " + tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2 -n 250 ";
stage("filter splitted", cmd);

hairpins = tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2.hairpins.tbl";

cmd = "perl scripts/sumirfold.pl " + tae + ".filtered " + tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2 " + scaff_db_ids
stage("sumirfold", cmd);	

	//remove all unuseful files
tae + ".filtered".rm()
tae + ".filtered.allhits".rm()
tae + ".filtered.allhits.perfectmatch".rm()
tae + ".filtered.allhits.perfectmatch.splitted".rm()
tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2".rm()
tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection".rm()
tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2".rm()
tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2.hairpins.fsa".rm()
tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2.rejects".rm()
tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2.seqtable".rm()
tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2.suspect.seqtable".rm()
tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2.suspecthairpins.fsa".rm()
tae + ".filtered.allhits.perfectmatch.splitted.perfectmatch2.selection2.suspecthairpins.tbl".rm()

scaff_db_ids + ".nhr".rm()
scaff_db_ids + ".nin".rm()
scaff_db_ids + ".nog".rm()
scaff_db_ids + ".nds".rm()
scaff_db_ids + ".nsi".rm()
scaff_db_ids + ".nsq".rm()
scaff_db_ids + ".nsq".rm()



cmd = "python scripts/result_format.py -files " + hairpins + " -o results_" + scaff_name + ".csv";
stage("result_format", cmd);

cmd = "python scripts/fasta_extractor.py -icsv results_" + scaff_name + ".csv -ifasta " + scaff + " -o scaff_results_" + scaff_name + ".fasta";
stage("fasta_extractor", cmd);

cmd = "python scripts/cluster.py -i results_" + scaff_name + ".csv -o cluster_" + scaff_name + ".csv -ml 500 -sl 200 -f scaff_results_" + scaff_name + ".fasta";
stage("cluster", cmd);

cmd = "python scripts/blast_trep.py -i cluster_" + scaff_name + ".csv -o cluster_trep_" + scaff_name + ".csv -db " + trep_db;
stage("blast_trep", cmd);

cmd = "python scripts/blast_IWGSC2.py -i cluster_trep_" + scaff_name + ".csv -o cluster_trep_IWGSC2_" + scaff_name + ".csv -db " + iWGSC2_db;
stage("blast_IWGSC2", cmd);

cmd = "python scripts/targetFinder.py -i results_" + scaff_name + ".csv -f " + iWGSC2_cDNA + " -o targets_" + scaff_name + ".csv ";
stage("targetFinder", cmd);

cmd = "python scripts/circos-data.py -c cluster_trep_IWGSC2_" + scaff_name + ".csv -t targets_" + scaff_name + ".csv -o scripts/libs/circos-0.67-6/miRNA/data/links.data";
stage("circos-data", cmd);

cmd = "./scripts/libs/circos-0.67-6/bin/circos -conf scripts/libs/circos-0.67-6/miRNA/etc/circos.conf";
stage("circos-plot", cmd);


//remove all unuseful files
"results_" + scaff_name + ".csv".rm()
"cluster_" + scaff_name + ".csv".rm()

scaff_db + ".nhr".rm()
scaff_db + ".nin".rm()
scaff_db + ".nsq".rm()
scaff_db + ".nsi".rm()
scaff_db + ".nog".rm()

trep_db + ".nhr".rm()
trep_db + ".nin".rm()
trep_db + ".nsq".rm()
trep_db + ".nsi".rm()
trep_db + ".nsd".rm()
trep_db + ".nog".rm()



void stage(string name, string cmd) {
	print "#####BEGIN AT#####\n";
	date = sys date;
	print "##################\n";
	print "Stage: " + name + "\n";
	print "Command: " + cmd + "\n";
	sys $cmd;
	print "END ##################\n";
}

**Comment by pcingola** [comment]
Hi, 
  You should submit a MINIMAL script that shows the issue (not 
your whole pipeline). Minimal means as few line as possible and 
self contained (I should be able to run it without requiring you to 
send me data files).
  Here are the general guidelines:

   http://pcingola.github.io/BigDataScript/about.html#bugs

  I hope this helps.

**Comment by juanmas07** [comment]
Ok now I have some more information to submit


This is the error I get when I execute the checkpoint:

line 1:0 token recognition error at: ''
Compiler messages:
ERROR [ file '' ] :	Could not compile /home/trigo/bds/18-3-15/checkpoint/split_scaffold_before.chp :LexerNoViableAltException('')


This is how I create the checkpoint

string chp_begin = "checkpoint/" + name + "_before.chp";

This is the command I was executing 

cmd = "python scripts/splitter.py --allhits " + tae + ".filtered.allhits.perfectmatch --fasta " + scaff + " -o " + scaff + ".splitted -n 250";

I would send you the checkpoint file if necessary, let me know how

**Comment by pcingola** [comment]
Please, take a look at the following guidelines 

   http://pcingola.github.io/BigDataScript/about.html#bugs

I hope you understand (after reading them carefully) that you are not 
reporting the information required to reproduce the error condition, thus 
I won't be able to help you out. This is not a bureaucratic requirement it 
is just that I really cannot reproduce the problem, which is necessary 
for debugging.

**Comment by juanmas07** [comment]
Here I go again:

    trigo@vzmarcosjuarez:~/bds/18-3-15$ sudo ./bds/bds checkpoint/blast_srna_before.chp 
line 1:0 token recognition error at: ''
    Compiler messages:
    ERROR [ file '' ] :	Could not compile /home/trigo/bds/18-3-15/checkpoint/blast_srna_before.chp :LexerNoViableAltException('')

I always get the same error when executing a checkpoint

BigDataScript version and sub-version numbers you are using

    BigDataScript 0.999h (build 2015-02-20),

Configuration file is as default

Full command line used to run the script
    sudo ./bds/bds checkpoint/blast_srna_before.chp 

I'm running Debian GNU/Linux 7

Let me know if I can send you anything else

**Comment by pcingola** [comment]
Two comments:

   i) The command 'bds checkpoint.chp' seems incorrect. You either execute 'bds script.bds' which 
   means normal script execution or you recover from a checkpoint using the 'recover' command 
    line option (i.e. 'bds -r checkpoint.chp'). It looks like the problem is that you forgot the '-r', thus 
    bds is trying to execute a checkpoint file as if it was a script, thus the confusion and the 'Could 
    not compile' message.

   ii) I'm not sure if running bds as root is a good idea...

I hope this helps.

**Comment by juanmas07** [comment]
excellent, my mistake. Thank you very much.

I'm running as sudo because sometimes files generated by a script are not accesible by another script resulting in a 'operation not permited' stuff.


Thank you again
