### ISSUE TITLE
Request to create a BDS community

### ISSUE THREAD

**Issue by kmhernan** [pcingola/BigDataScript#86]
I can see more and more people getting quite involved with helping @pcingola  debug BDS and provide suggestions. I am wondering if it would be an appropriate time for someone to create some kind of community (google groups??) for BDS. Of course bug reports are probably best dealt with here, but as someone who has become quite fond of BDS and can see its power (and hopefully people outside of bioinformatics will also start to see it), I am interested in learning about cool implementations, "add-ons", etc. that people are using. Some examples:

* my colleagues and I are about to submit a paper for a fully automated pipeline that relies heavily on BDS (and will be available as an EC2 image). Of course we will cite, but I think it would be really cool to have a place to share such implementations with the community as some people may find it a good way to learn, or even have suggestions to make it better (from a BDS implementation side, not a bioinformatics side)
* I want to have syntax highlighting for BDS in VIM and maybe someone has already implemented this, or has experience in creating new syntax files for VIM (please share if so!)
* BDS design patterns! I spent so much time struggling with designing my pipeline's structure, especially with nested `par()` statements. It could be a great place to ask those kinds of questions.
* Although it doesn't appear to be an "official" setting, perhaps some people have done something cool with the YAML output from BDS runs (e.g., created pretty DAGs, HTML files, or pushed it into some bigger database)

Despite the community being small, I would personally like to start up an online discussion place. I am perfectly willing to create something with google groups, but perhaps Pablo would like to as I think it would be quite necessary for you to be involved. Or maybe everyone thinks it's a terrible idea! I just don't want to flood the issues page with topics that may be better suited for a discussion board. Let me know BDS community!

Kyle

**Comment by pcingola** [comment]
Hi Kyle,
  I think this is a great idea for all the reasons you mentioned. For instance, a place 
where we can  exchanging "gold standard" analysis pipelines (e.g. re-sequencing/variant 
discovery, RNA-Seq, Chip-seq, etc.) would save tons of time for everyone since we 
are not constantly re-inventing the wheel. 
   How do you see yourself leading this effort? ...the problem of having a good idea 
is that you might be the best person to implement it :-P
  Yours

    Pablo

**Comment by kmhernan** [comment]
@pcingola I think it would be as simple as creating a google groups account and then you would have to add a link somewhere to advertise. I have only dealt with google groups a little bit, but I don't think it's too terribly difficult.

**Comment by kmhernan** [comment]
So i created one: https://groups.google.com/d/forum/bigdatascript-users

I will add you as an admin when you join

**Comment by pcingola** [comment]
Great!

**Comment by pcingola** [comment]
Added link from bds's page.

**Comment by pcingola** [comment]
Closing: The google group was created. 
Thank you Kyle!
