### ISSUE TITLE
YAML and HTML report

### ISSUE THREAD

**Issue by riyuebao** [pcingola/BigDataScript#87]
@pcingola 

Hi Pablo,

I was wondering is it possible to generate the BDS report in YAML and HTML format at the same time? We love the YAML report for collecting stats and creating our own plots, and it would also be nice to have the HTML report to interactively view the dependency map and the runtime bar charts.

Thank you!

Best,
Riyue Bao
The University of Chicago

**Comment by pcingola** [comment]
It is not possible at the moment, but I'll add it as a new feature...

**Comment by pcingola** [comment]
Done.
Both YAML and HTML reports can be created using command line options: '-reportHtml', '-reportYaml', 'noReportHtml', and '-noReportHtml'
