### ISSUE TITLE
Stuck in "too many threads running" loop

### ISSUE THREAD

**Issue by kmhernan** [pcingola/BigDataScript#88]
I am trying to test a pipeline with 100 samples. I can get everything to work fine with 4 samples. Now, I am having strange issues which I'm not sure how to handle. I seem to get stuck in a loop that keeps printing:

```
00:48:15.101	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
00:48:15.601	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
00:48:16.101	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
00:48:16.602	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
00:48:17.102	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
00:48:17.602	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
00:48:18.102	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
00:48:18.603	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
00:48:19.103	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
00:48:19.603	ExecutionerClusterSge 'ClusterSge[26]': INFO: Too many threads running (207). Waiting for some threads to finish.
```

I have been waiting for quite some time (30 min) and it just keeps printing this. Strangely, no jobs are in queue now or are running. BDS just seems to be hanging. I don't see any other threads running when executing `ps -eFl`. I don't know a good way to reproduce this at the moment, but perhaps you have general thoughts??

**Comment by kmhernan** [comment]
A bit more looking at the source, I think I found a bug:

```
	public int getWaitAfterTaskRun() {
		if (waitAfterTaskRun <= 0) {
			// Parse property
			maxThreads = (int) getLong(WAIT_AFTER_TASK_RUN, DEFAULT_WAIT_AFTER_TASK_RUN);
			if (debug) Timer.showStdErr("Config: Setting 'waitAfterTaskRun' to " + waitAfterTaskRun);
		}

		return waitAfterTaskRun;
	}
```

You are setting the `maxThreads` variable here instead of the `waitAfterTaskRun`. This is line 289 in `Config.java`

**Comment by kmhernan** [comment]
And another discovery... I find the following exception:

```
Exception in thread "Thread-10" 00:00:02.960	Parallel 'ExScaliburSMD-run.bds.20150330_200654_094_parallel_9_parallel_23' execution finished
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$KeyIterator.next(HashMap.java:956)
	at ca.mcgill.mcb.pcingola.bigDataScript.task.TaskDependecies.isTasksDone(TaskDependecies.java:381)
	at ca.mcgill.mcb.pcingola.bigDataScript.task.TaskDependecies.waitTasksAll(TaskDependecies.java:485)
	at ca.mcgill.mcb.pcingola.bigDataScript.run.BigDataScriptThread.waitAll(BigDataScriptThread.java:1654)
	at ca.mcgill.mcb.pcingola.bigDataScript.run.BigDataScriptThread.run(BigDataScriptThread.java:1185)
```

When I am using the `-v` flag, it calls the `isTaskDone()` function in `TaskDependencies.java` which throws this `java.util.ConcurrentModificationException` ... I reran the same BDS script without the `-v` flag and haven't seen this popup

**Comment by pcingola** [comment]
Thank you!
I'll try to take a look at it soon.

**Comment by pcingola** [comment]
Fixed Config. getWaitAfterTaskRun() and added 'syncronized' to TaskDependecies.isTasksDone().
Thank you!

**Comment by pcingola** [comment]
Now 'maxThreads' in the config file is checked against a minimum 
value (MAX_NUMBER_OF_RUNNING_THREADS_MIN_VALUE = 50). 
If the number is too small (e.g. setting it to 0 by mistake), then we show an error message and set it so 'MAX_NUMBER_OF_RUNNING_THREADS_MIN_VALUE'

This should avoid your problem under most circumstances (all I can think of :-).
Please reopen this issue if you see the problem again.
