### ISSUE TITLE
Saturated NFS file systems: Problems with output files

### ISSUE THREAD

**Issue by pcingola** [pcingola/BigDataScript#89]
Some cluster's NFS file systems may take a long time to propagate file 
status. As a results, when a slave node finishes processing the output files
appear to be empty on the head node, thus causing a "task failed" error.

We need a more robust method for propagating results, e.g. by writing the file 
status on the exitCode file (where proper empty condition is checked upon).

**Comment by kmhernan** [comment]
I have had this problem and I ended up adding a significant sleep to each task, which of course isn't favorable. It only happens when I am using small test data and the tasks are then very short.

**Comment by pcingola** [comment]
Closing old issues, feel free to re-open.
