### ISSUE TITLE
Add ability to change the working directory

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#90]
Perhaps using a chdir function on string data type

**Comment by pcingola** [comment]
Done:

    newDir := "my/dir/for/data/and/programs"
    newDir.chdir()

This seemed deceitfully simple, but it was a lot of work! 
It turns out that I had to refactor quite a lot of code to make 
this happen since Java doesn't have the concept of 
"current dir" (at least not in the same way as Unix does).
