### ISSUE TITLE
0 length output file causes task to be considered as failed

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#91]
I have a task that runs Picards SamToFastQ which creates three files, 1 and 2 of paired fastq files and an unpaired file.  For my samples, the unpaired file may or may not be empty, but when they are, BDS thinks the task failed.  How can I tell BDS this is ok or to ignore file sizes for this particular task?

**Comment by pcingola** [comment]
You can set 'allowEmpty', the task/dep statement would be something like:

    task( ... , allowEmpty:=true ) { ...

I hope this helps.

**Comment by pcingola** [comment]
Closing. I think this one was solved, feel free to re-open.
