### ISSUE TITLE
website updates?

### ISSUE THREAD

**Issue by jasonsydes** [pcingola/BigDataScript#92]
(I originally posted this on the BigDataScript-users list; @kmhernan suggested I create an issue here.)

I've been looking for a good pipeline system for awhile now, and I just discovered BDS.  It looks very promising, and I'll be trying it out for some of my work.  Thank you for all your hard work on it!

I spent some time this weekend reading through most of the documentation (very well documented, thank you for that as well!).  I noticed a few typos / spelling errors in the documentation, and I'd like to help you fix them.  I figured it would be easiest to fix them and send you a pull request, but I don't know if the BDS website is checked into a GitHub repo anywhere? I couldn't seem to find it in [this repository](https://github.com/pcingola/BigDataScript) or in https://github.com/pcingola/pcingola.github.io.  Maybe I'm looking in the wrong place?

Thanks again for your contribution to the community Pablo!

**Comment by pcingola** [comment]
Hi Jason,
   Yes, a pull request would be perfect. The pages are in GIT's 
branch "origin/gh-pages", so you can modify them directly there.
  Thank you!

     Pablo

**Comment by jasonsydes** [comment]
Thanks Pablo, working on it now...

**Comment by jasonsydes** [comment]
Ok, pull request #93 addresses this.

**Comment by pcingola** [comment]
PR merged. Thank you.
