### ISSUE TITLE
tiny?  Name log files after taskName (if present)

### ISSUE THREAD

**Issue by jasonsydes** [pcingola/BigDataScript#94]
Currently the only thing that `taskName` does is name tasks in the report ([as far as the docs say at least](http://pcingola.github.io/BigDataScript/bigDataScript_manual.html#taskExpr)).

It might be nice to name the files in the log directory by their `taskName`s.

So, currently, a job I'm running has a log dir that looks like this:
```
task.go.line_14.id_1.sh
task.go.line_14.id_1.stderr
task.go.line_14.id_1.stdout
task.go.line_14.id_2.sh
task.go.line_14.id_2.stderr
task.go.line_14.id_2.stdout
task.go.line_14.id_3.sh
task.go.line_14.id_3.stderr
task.go.line_14.id_3.stdout
```
It might be more helpful if directory had the following filenames instead:
```
task.go.myTaskName.line_14.id_1.sh
task.go.myTaskName.line_14.id_1.stderr
task.go.myTaskName.line_14.id_1.stdout
task.go.myTaskName.line_14.id_2.sh
task.go.myTaskName.line_14.id_2.stderr
task.go.myTaskName.line_14.id_2.stdout
task.go.myTaskName.line_14.id_3.sh
task.go.myTaskName.line_14.id_3.stderr
task.go.myTaskName.line_14.id_3.stdout
```

**Comment by pcingola** [comment]
Yes, that would be useful. I'll try to add it....

**Comment by pcingola** [comment]
Done.
Now when you run this code:

    tid := task (taskName := "mytask" ) sys echo hi
    print "task ID: '$tid'\n"

The output is:

    $ bds -log z.bds
    task ID: 'z.bds.20150422_102737_876/task.z.mytask.line_3.id_1'
    hi

And the files are:

    $ ls -al z.bds.20150422_102737_876
    total 24
    drwxr-xr-x  6 pcingola  staff  204 22 Apr 10:27 .
    drwxr-xr-x  6 pcingola  staff  204 22 Apr 10:27 ..
    -rw-r--r--  1 pcingola  staff    1 22 Apr 10:27 task.z.mytask.line_3.id_1.exitCode
    -rwxr--r--  1 pcingola  staff   49 22 Apr 10:27 task.z.mytask.line_3.id_1.sh
    -rw-r--r--  1 pcingola  staff    0 22 Apr 10:27 task.z.mytask.line_3.id_1.stderr
    -rw-r--r--  1 pcingola  staff    3 22 Apr 10:27 task.z.mytask.line_3.id_1.stdout

Enjoy!

**Comment by jasonsydes** [comment]
Great! Thanks Pablo!!
