### ISSUE TITLE
can I change default path to bds.config?

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#97]
I installed bds for global use on my sge cluster. It works quite well.

But bds always reads bds.config from $HOME/.bds/bds.config if I don't specify path for it with -c parameter.

How can I change it to something like /specific/path/to/bds/bds.config?

I should be able to change the default path because colleagues working on my cluster don't want to add -c parameter for all their jobs...

**Comment by leepc12** [comment]
I fixed it myself, thanks

**Comment by pcingola** [comment]
Hi, once more, sorry for the long delay answering, I was out of town.
If you'd like to share your code, please send a PR and I'll be glad to merge it.
